# Generated by Django 2.2.24 on 2022-02-05 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('defraiement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reunion',
            name='adresse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bourseLibre.Adresse'),
        ),
    ]
