# Generated by Django 2.2.24 on 2022-02-05 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defraiement', '0002_auto_20220205_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participantreunion',
            name='reunion',
        ),
        migrations.AddField(
            model_name='reunion',
            name='participants',
            field=models.ManyToManyField(help_text="Le participant doit etre associé à une reunion existante (sinon créez d'abord la reunion)", to='defraiement.ParticipantReunion'),
        ),
    ]
