# Generated by Django 2.2.24 on 2022-02-06 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defraiement', '0003_auto_20220205_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantreunion',
            name='distance',
            field=models.TextField(blank=True, null=True, verbose_name='Description du contexte'),
        ),
    ]
