# Generated by Django 2.2.27 on 2022-05-01 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defraiement', '0007_distance_participantreunion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participantreunion',
            name='contexte_distance',
        ),
        migrations.AddField(
            model_name='distance_participantreunion',
            name='contexte_distance',
            field=models.TextField(blank=True, null=True, verbose_name='Description du contexte'),
        ),
    ]
