# Generated by Django 2.2.27 on 2022-05-01 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('defraiement', '0008_auto_20220501_2205'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='distance_participantreunion',
            unique_together={('reunion', 'participant')},
        ),
    ]
