# Generated by Django 2.2.27 on 2022-05-01 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defraiement', '0010_auto_20220501_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reunion',
            name='categorie',
            field=models.CharField(choices=[('0', 'Réunion équipe'), ('1', 'Troc de Graine'), ('2', 'Atelier'), ('3', 'Rencontre'), ('4', 'Réunion FestiGraines'), ('5', 'Autre')], default='0', max_length=30, verbose_name='categorie'),
        ),
    ]
