# Generated by Django 2.2.28 on 2022-08-15 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('defraiement', '0011_auto_20220501_2326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participantreunion',
            name='distance',
        ),
    ]
