# Generated by Django 2.2.28 on 2022-10-31 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0084_auto_20221030_2105'),
        ('defraiement', '0012_remove_participantreunion_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantreunion',
            name='asso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bourseLibre.Asso'),
        ),
    ]
