# Generated by Django 2.2.28 on 2022-11-13 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defraiement', '0013_participantreunion_asso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reunion',
            name='categorie',
            field=models.CharField(choices=[('0', 'Réunion équipe'), ('1', 'Troc de Graine'), ('2', 'Atelier'), ('3', 'Rencontre'), ('4', 'Réunion FestiGraines'), ('5', 'Autre'), ('6', 'Cercle Ancrage'), ('7', 'Cercle thématique'), ('8', 'Cercle Education'), ('9', 'Evenement'), ('10', 'Autre')], default='0', max_length=30, verbose_name='categorie'),
        ),
    ]
