# Generated by Django 2.1.11 on 2019-12-02 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import taggit.managers
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atelier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('0', 'Bases de la permaculture'), ('1', 'Conception du jardin'), ('2', 'Réalisation du jardin'), ('3', 'Récolter')], default='0', max_length=30, verbose_name='categorie')),
                ('statut', models.CharField(choices=[('0', 'proposition'), ('1', "accepté, en cours d'organisation")], default='proposition', max_length=30, verbose_name='statut de la atelier')),
                ('titre', models.CharField(max_length=120)),
                ('slug', models.SlugField(default=uuid.uuid4, max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('objectif', models.TextField(blank=True, null=True)),
                ('matériel', models.TextField(blank=True, null=True)),
                ('référent', models.TextField(blank=True, null=True)),
                ('date_atelier', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date prévue')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de parution')),
                ('date_modification', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de modification')),
                ('date_dernierMessage', models.DateTimeField(auto_now=True, verbose_name='Date du dernier message')),
                ('dernierMessage', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('participants', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='Une liste de mots clés, séparés par des virgules.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Mots-clés')),
            ],
            options={
                'ordering': ('-date_creation',),
            },
        ),
        migrations.CreateModel(
            name='CommentaireAtelier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('atelier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ateliers.Atelier')),
                ('auteur_comm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
