# Generated by Django 2.1.11 on 2019-12-02 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ateliers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atelier',
            name='matériel',
            field=models.TextField(blank=True, null=True, verbose_name='Matériel nécessaire'),
        ),
        migrations.AlterField(
            model_name='atelier',
            name='objectif',
            field=models.TextField(blank=True, null=True, verbose_name="Objectif de l'atelier"),
        ),
        migrations.AlterField(
            model_name='atelier',
            name='référent',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Référent(e.s)'),
        ),
    ]
