# Generated by Django 2.1.11 on 2019-12-02 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ateliers', '0002_auto_20191202_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atelier',
            name='categorie',
            field=models.CharField(choices=[('0', 'Permaculture'), ('1', 'Bricolage'), ('2', 'Cuisine'), ('3', 'Bien-être'), ('4', 'Musique'), ('5', 'Autre...')], default='0', max_length=30, verbose_name='categorie'),
        ),
    ]
