# Generated by Django 2.1.11 on 2019-12-04 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ateliers', '0003_auto_20191202_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atelier',
            name='objectif',
        ),
    ]
