# Generated by Django 2.1.11 on 2019-12-04 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ateliers', '0004_remove_atelier_objectif'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atelier',
            old_name='matériel',
            new_name='materiel',
        ),
    ]
