# Generated by Django 2.2.8 on 2019-12-09 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ateliers', '0006_inscriptionatelier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atelier',
            old_name='référent',
            new_name='referent',
        ),
    ]
