# Generated by Django 2.2.8 on 2019-12-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ateliers', '0007_auto_20191209_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atelier',
            name='participants',
        ),
        migrations.AlterField(
            model_name='atelier',
            name='statut',
            field=models.CharField(choices=[('0', 'proposition'), ('1', "accepté, en cours d'organisation")], default='proposition', max_length=30, verbose_name="Statut de l'atelier"),
        ),
    ]
