# Generated by Django 2.2.8 on 2019-12-10 01:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ateliers', '0011_auto_20191209_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='atelier',
            name='duree_prevue',
            field=models.TimeField(blank=True, default=django.utils.timezone.now, help_text="Durée de l'atelier estimée", null=True, verbose_name='Durée prévue'),
        ),
        migrations.AddField(
            model_name='atelier',
            name='tarif_par_personne',
            field=models.CharField(default='gratuit', max_length=30, verbose_name="Tarif de l'atelier par personne"),
        ),
    ]
