# Generated by Django 2.2.8 on 2019-12-10 01:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ateliers', '0012_auto_20191210_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='atelier',
            name='auteur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='atelier',
            name='date_atelier',
            field=models.DateField(blank=True, default=django.utils.timezone.now, help_text='Date prévue', null=True, verbose_name='Date prévue'),
        ),
        migrations.AlterField(
            model_name='atelier',
            name='duree_prevue',
            field=models.TimeField(blank=True, default='02:00', help_text="Durée de l'atelier estimée", null=True, verbose_name='Durée prévue'),
        ),
        migrations.AlterField(
            model_name='atelier',
            name='heure_atelier',
            field=models.TimeField(blank=True, default='17:00', help_text='Heure prévue', null=True, verbose_name='Heure prévue'),
        ),
        migrations.AlterField(
            model_name='atelier',
            name='tarif_par_personne',
            field=models.CharField(default='gratuit', help_text="Tarif de l'atelier par personne", max_length=30, verbose_name="Tarif de l'atelier par personne"),
        ),
    ]
