# Generated by Django 2.2.8 on 2020-01-06 16:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ateliers', '0013_auto_20191210_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atelier',
            name='date_atelier',
            field=models.DateField(blank=True, default=django.utils.timezone.now, help_text='(jj/mm/an)', null=True, verbose_name='Date prévue'),
        ),
        migrations.AlterField(
            model_name='atelier',
            name='dernierMessage',
            field=models.CharField(blank=True, default=None, help_text='Heure prévue (hh:mm)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='atelier',
            name='heure_atelier',
            field=models.TimeField(blank=True, default='17:00', help_text='(hh:mm)', null=True, verbose_name='Heure prévue'),
        ),
    ]
