# Generated by Django 2.2.8 on 2020-01-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ateliers', '0014_auto_20200106_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='atelier',
            name='outils',
            field=models.TextField(blank=True, null=True, verbose_name='Outils nécessaire'),
        ),
    ]
