# Generated by Django 2.2.8 on 2020-01-10 15:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ateliers', '0015_atelier_outils'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atelier',
            name='date_atelier',
            field=models.DateField(blank=True, default=django.utils.timezone.now, help_text='(jj/mm/an)', null=True, verbose_name="Date prévue (affichage dans l'agenda)"),
        ),
    ]
