# Generated by Django 2.2.13 on 2020-08-25 18:52

from django.db import migrations, models
import django.db.models.deletion

from blog.models import Article, Projet
from bourseLibre.models import Asso


def combine_names(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    article = apps.get_model('ateliers', 'Atelier')
    assos = apps.get_model('bourseLibre', 'Asso')
    asso_public, created = assos.objects.get_or_create(nom='Public')
    asso_permacat, created = assos.objects.get_or_create(nom='Permacat')
    for prod in article.objects.all():
        if prod.estPublic:
            prod.asso = asso_public
        else:
            prod.asso = asso_permacat
        prod.save()
    for prod in Projet.objects.all():
        if prod.estPublic:
            prod.asso = asso_public
        else:
            prod.asso = asso_permacat
        prod.save()

class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0033_auto_20200825_2014'),
        ('ateliers', '0016_auto_20200110_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='atelier',
            name='asso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bourseLibre.Asso'),
        ),

    ]
