# Generated by Django 2.2.13 on 2021-04-06 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ateliers', '0018_auto_20210312_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atelier',
            name='date_dernierMessage',
            field=models.DateTimeField(verbose_name='Date du dernier message'),
        ),
    ]
