# Generated by Django 2.2.24 on 2021-07-06 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0058_auto_20210619_2341'),
        ('ateliers', '0021_merge_20210406_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='atelier',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Article'),
        ),
    ]
