# Generated by Django 2.2.24 on 2021-07-06 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ateliers', '0022_atelier_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='atelier',
            name='estArchive',
            field=models.BooleanField(default=False, verbose_name="Archiver l'atelier"),
        ),
    ]
