# Generated by Django 2.2.24 on 2021-07-06 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ateliers', '0023_atelier_estarchive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atelier',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Article'),
        ),
    ]
