# Generated by Django 2.2.24 on 2021-07-15 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ateliers', '0025_auto_20210713_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atelier',
            name='tarif_par_personne',
            field=models.CharField(default='gratuit', help_text="Tarif de l'atelier par personne", max_length=100, verbose_name="Tarif de l'atelier par personne"),
        ),
    ]
