# Generated by Django 2.2.24 on 2022-01-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ateliers', '0027_auto_20210829_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atelier',
            name='categorie',
            field=models.CharField(choices=[('0', 'Permaculture'), ('1', 'Bricolage'), ('2', 'Cuisine'), ('3', 'Bien-être'), ('4', 'Musique'), ('6', 'Politique'), ('5', 'Autre...')], default='0', max_length=30, verbose_name='categorie'),
        ),
    ]
