# Generated by Django 2.2.27 on 2022-03-31 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ateliers', '0028_auto_20220112_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atelier',
            name='statut',
            field=models.CharField(choices=[('0', 'proposition'), ('1', "accepté, en cours d'organisation"), ('2', "accepté, s'est déroule correctement"), ('3', 'a été annulé'), ('4', 'Activité professionnelle')], default='proposition', max_length=30, verbose_name="Statut de l'atelier"),
        ),
    ]
