# Generated by Django 2.2.27 on 2022-07-24 13:12

from django.db import migrations, models
import datetime as dt


def combine_names(apps, schema_editor):
    ateliers = apps.get_model('ateliers', 'Atelier')
    for art in ateliers.objects.all():
        if art.duree_prevue and art.start_time:
            delta = dt.timedelta(hours=art.duree_prevue.hour, minutes=art.duree_prevue.minute)
            art.heure_atelier_fin = dt.datetime.combine(art.start_time, art.heure_atelier) + delta
        else:
            art.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ateliers', '0030_auto_20220331_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='atelier',
            name='heure_atelier_fin',
            field=models.TimeField(blank=True, default='19:00', help_text='Horaire de fin (hh:mm)', null=True, verbose_name='Heure de fin '),
        ),
        migrations.AlterField(
            model_name='atelier',
            name='heure_atelier',
            field=models.TimeField(blank=True, default='17:00', help_text='Horaire de départ (hh:mm)', null=True, verbose_name='Heure de début'),
        ),

        migrations.RunPython(combine_names, ),
        migrations.RemoveField(
            model_name='atelier',
            name='duree_prevue',
        ),
    ]
