# Generated by Django 2.2.28 on 2022-08-22 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ateliers', '0031_auto_20220724_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atelier',
            name='categorie',
            field=models.CharField(choices=[('0', 'Permaculture'), ('1', 'Bricolage'), ('2', 'Cuisine'), ('3', 'Bien-être'), ('4', 'Musique'), ('6', 'Politique'), ('5', 'Autre...'), ('7', 'Professionel')], default='0', max_length=30, verbose_name='categorie'),
        ),
    ]
