# Generated by Django 2.2.28 on 2022-08-22 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ateliers', '0032_auto_20220822_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atelier',
            name='categorie',
            field=models.CharField(choices=[('0', 'Permaculture'), ('1', 'Bricolage'), ('2', 'Cuisine'), ('3', 'Bien-être'), ('4', 'Musique'), ('6', 'Politique'), ('5', 'Autre...'), ('7', 'Activité Pro')], default='0', max_length=30, verbose_name='categorie'),
        ),
        migrations.AlterField(
            model_name='atelier',
            name='statut',
            field=models.CharField(choices=[('0', 'proposition'), ('1', "accepté, en cours d'organisation"), ('2', "accepté, s'est déroule correctement"), ('3', 'a été annulé')], default='proposition', max_length=30, verbose_name="Statut de l'atelier"),
        ),
    ]
