# Generated by Django 2.2.8 on 2020-06-15 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Votation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_vote', models.CharField(choices=[('', '-----------'), ('0', "Vote d'un projet"), ('1', "Vote d'une décision"), ('2', 'Sondage')], default='2', max_length=30, verbose_name='Type de vote')),
                ('titre', models.CharField(max_length=100)),
                ('question', models.CharField(max_length=100, verbose_name='Question soumise au vote')),
                ('slug', models.SlugField(max_length=100)),
                ('contenu', models.TextField(null=True)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de parution')),
                ('estPublic', models.BooleanField(default=False, verbose_name='Public ou réservé aux membres permacat')),
                ('date_dernierMessage', models.DateTimeField(auto_now=True, verbose_name='Date du dernier message')),
                ('date_modification', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de modification')),
                ('estArchive', models.BooleanField(default=False, verbose_name='Archiver la proposition')),
                ('estAnonyme', models.BooleanField(default=False, verbose_name='Vote anonyme')),
                ('start_time', models.DateTimeField(help_text='jj/mm/année', null=True, verbose_name='Date de début')),
                ('end_time', models.DateTimeField(help_text='jj/mm/année', null=True, verbose_name='Date de fin')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auteur_votation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'votation',
                'ordering': ('-date_creation',),
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choix', models.CharField(choices=[('', '-----------'), ('0', 'Oui'), ('1', 'Non'), ('2', 'Ne se prononce pas')], default='', max_length=30, verbose_name='')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de parution')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auteur_vote', to=settings.AUTH_USER_MODEL)),
                ('votation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auteur_vote', to='vote.Votation')),
            ],
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('auteur_comm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auteur_comm_vote', to=settings.AUTH_USER_MODEL)),
                ('votation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.Votation')),
            ],
        ),
    ]
