# Generated by Django 2.2.24 on 2021-12-03 20:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bourseLibre', '0060_auto_20211203_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposition_m',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposition', models.CharField(max_length=500, verbose_name='Proposition')),
            ],
        ),
        migrations.CreateModel(
            name='Question_binaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Question (oui/non) soumise au vote ?')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Suffrage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_vote', models.CharField(choices=[('', '-----------'), ('0', "Vote d'un projet"), ('1', "Vote d'une décision"), ('2', 'Sondage'), ('3', 'Election')], default='', max_length=30, verbose_name='Type de vote')),
                ('titre', models.CharField(max_length=100, verbose_name='Titre du sondage')),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField(null=True, verbose_name='Description du contexte')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de parution')),
                ('date_dernierMessage', models.DateTimeField(blank=True, null=True, verbose_name='Date du dernier message')),
                ('date_modification', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de modification')),
                ('estArchive', models.BooleanField(default=False, verbose_name='Archiver la proposition')),
                ('estAnonyme', models.BooleanField(default=False, verbose_name='Vote anonyme')),
                ('start_time', models.DateField(help_text='jj/mm/année', null=True, verbose_name='Date de début du vote')),
                ('end_time', models.DateField(help_text='jj/mm/année', null=True, verbose_name='Date de fin du vote')),
                ('asso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bourseLibre.Asso')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auteur_suffrage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'suffrage',
                'ordering': ('-date_creation',),
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de parution')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('commentaire', models.TextField(null=True, verbose_name='Commentaire')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auteur_vote', to=settings.AUTH_USER_MODEL)),
                ('suffrage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suffrage', to='vote.Suffrage')),
            ],
            options={
                'unique_together': {('auteur', 'suffrage')},
            },
        ),
        migrations.CreateModel(
            name='ReponseQuestion_m',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choix', models.IntegerField(choices=[('', '-----------'), (0, "pas du tout d'accord"), (1, "Plutot pas d'accord"), (2, 'Neutre'), (3, "Plutot d'accord"), (4, "Tout à fait d'accord")], default=2, verbose_name='Choix du vote :')),
                ('proposition', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='propos_question_m', to='vote.Proposition_m')),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rep_question_m', to='vote.Vote')),
            ],
        ),
        migrations.CreateModel(
            name='ReponseQuestion_b',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choix', models.IntegerField(choices=[('', '-----------'), (0, 'Oui'), (1, 'Non'), (2, 'Ne se prononce pas')], default=2, verbose_name='Choix du vote :')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.Question_binaire')),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rep_question_b', to='vote.Vote')),
            ],
        ),
        migrations.CreateModel(
            name='Question_majoritaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Question (jugement majoritaire) soumise au vote :')),
                ('suffrage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.Suffrage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='question_binaire',
            name='suffrage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.Suffrage'),
        ),
        migrations.AddField(
            model_name='proposition_m',
            name='question_m',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.Question_majoritaire'),
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('auteur_comm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auteur_comm_vote', to=settings.AUTH_USER_MODEL)),
                ('suffrage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.Suffrage')),
            ],
        ),
    ]
