# Generated by Django 2.2.24 on 2021-08-12 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_auto_20210812_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reponsequestion_b',
            name='choix',
        ),
        migrations.RemoveField(
            model_name='reponsequestion_m',
            name='choix',
        ),
    ]
