# Generated by Django 2.2.28 on 2022-11-27 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_suffrage_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposition_m',
            name='type_choix',
            field=models.CharField(choices=[('', '-----------'), ('0', "Opinion: de 'pas du tout d'accord' à 'tout à fait d'accord"), ('1', 'Note : de 0 à 4'), ('2', "Appréciation : de 'pas du tout satisfaisant' à 'tout à fait satisfaisant'")], default='', max_length=30, verbose_name='Type de notation'),
        ),
        migrations.AlterField(
            model_name='reponsequestion_m',
            name='choix',
            field=models.IntegerField(choices=[('', 'Exprimez votre opinion'), (0, "pas du tout d'accord"), (1, "Plutot pas d'accord"), (2, 'Neutre'), (3, "Plutot d'accord"), (4, "Tout à fait d'accord")], default=2, verbose_name='Choix du vote :'),
        ),
    ]
