# Generated by Django 2.2.13 on 2020-08-18 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_auto_20200818_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suffrage',
            name='contenu',
            field=models.TextField(null=True, verbose_name='Description du contexte'),
        ),
    ]
