# Generated by Django 2.2.13 on 2020-08-18 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0004_auto_20200818_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='commentaire',
            field=models.TextField(null=True, verbose_name='Commentaire'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='auteur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auteur_vote', to=settings.AUTH_USER_MODEL),
        ),
    ]
