# Generated by Django 2.2.28 on 2022-11-27 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0004_auto_20221127_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposition_m',
            name='type_choix',
        ),
        migrations.AddField(
            model_name='question_majoritaire',
            name='type_choix',
            field=models.CharField(choices=[('', '-----------'), ('0', "Opinion: de 'pas du tout d'accord' à 'tout à fait d'accord"), ('1', 'Note : de 0 à 4'), ('2', "Appréciation : de 'pas du tout satisfaisant' à 'tout à fait satisfaisant'")], default='0', max_length=30, verbose_name='Type de notation'),
        ),
    ]
