# Generated by Django 2.2.24 on 2021-08-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0004_auto_20210812_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='reponsequestion_b',
            name='choix',
            field=models.IntegerField(choices=[('', '-----------'), (0, 'Oui'), (1, 'Non'), (2, 'Ne se prononce pas')], default=2, verbose_name='Choix du vote :'),
        ),
        migrations.AddField(
            model_name='reponsequestion_m',
            name='choix',
            field=models.IntegerField(choices=[('', '-----------'), (0, "pas du tout d'accord"), (1, "Plutot pas d'accord"), (2, 'Neutre'), (3, "Plutot d'accord"), (4, "Tout à fait d'accord")], default=2, verbose_name='Choix du vote :'),
        ),
    ]
