# Generated by Django 2.2.13 on 2020-08-19 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0005_auto_20200818_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='choix',
            field=models.CharField(choices=[('', '-----------'), ('0', 'Oui'), ('1', 'Non'), ('2', 'Ne se prononce pas')], default='', max_length=30, verbose_name='Choix du vote :'),
        ),
    ]
