# Generated by Django 2.2.28 on 2022-12-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0005_auto_20221127_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_majoritaire',
            name='type_choix',
            field=models.CharField(choices=[('', '-----------'), ('0', "Opinion: de 'pas du tout d'accord' à 'tout à fait d'accord"), ('1', 'Note : de 0 à 4'), ('2', "Appréciation : de 'pas du tout satisfaisant' à 'tout à fait satisfaisant'")], default='0', max_length=30, verbose_name='Type de choix de vote'),
        ),
        migrations.AlterField(
            model_name='reponsequestion_m',
            name='choix',
            field=models.IntegerField(choices=[('', '------------ Exprimez votre opinion --------------'), (0, "pas du tout d'accord"), (1, "Plutot pas d'accord"), (2, 'Neutre'), (3, "Plutot d'accord"), (4, "Tout à fait d'accord")], default=2, verbose_name='Choix du vote :'),
        ),
    ]
