# Generated by Django 2.2.24 on 2021-08-18 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0005_auto_20210812_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reponsequestion_b',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.Question_binaire'),
        ),
    ]
