# Generated by Django 2.2.24 on 2021-09-17 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0008_auto_20210907_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suffrage',
            name='end_time',
            field=models.DateField(help_text='jj/mm/année', null=True, verbose_name='Date de fin du vote'),
        ),
        migrations.AlterField(
            model_name='suffrage',
            name='start_time',
            field=models.DateField(help_text='jj/mm/année', null=True, verbose_name='Date de début du vote'),
        ),
    ]
