# Generated by Django 2.2.24 on 2021-11-24 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0009_auto_20210917_2158'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Proposition_m',
        ),
    ]
