# Generated by Django 2.2.13 on 2021-04-06 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0008_auto_20210312_0158'),
        ('vote', '0009_auto_20210406_2056'),
    ]

    operations = [
    ]
