# Generated by Django 2.2.24 on 2021-07-28 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0010_merge_20210406_2132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suffrage',
            old_name='contenu',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='suffrage',
            name='estPublic',
        ),
        migrations.RemoveField(
            model_name='suffrage',
            name='question',
        ),
        migrations.AddField(
            model_name='suffrage',
            name='titre',
            field=models.CharField(default='', max_length=100, verbose_name='Titre du sondage'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Question_majoritaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100, verbose_name='Question soumise au jugement majoritaire ?')),
                ('suffrage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.Suffrage')),
            ],
        ),
        migrations.CreateModel(
            name='Question_binaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100, verbose_name='Question soumise au vote ?')),
                ('suffrage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.Suffrage')),
            ],
        ),
    ]
