# Generated by Django 2.2.24 on 2021-11-25 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0011_auto_20211124_2213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposition_m',
            old_name='question',
            new_name='question_m',
        ),
    ]
