# Generated by Django 2.2.24 on 2021-07-29 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0011_auto_20210728_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_binaire',
            name='question',
            field=models.CharField(max_length=100, verbose_name='Question (oui/non) soumise au vote ?'),
        ),
        migrations.AlterField(
            model_name='question_majoritaire',
            name='question',
            field=models.CharField(max_length=100, verbose_name='Question (jugement majoritaire) soumise au vote ?'),
        ),
    ]
