# Generated by Django 2.2.24 on 2021-11-25 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0013_auto_20211125_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reponsequestion_m',
            name='proposition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propos_question_m', to='vote.Proposition_m'),
        ),
    ]
