# Generated by Django 2.2.24 on 2021-07-29 22:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vote', '0013_auto_20210729_1641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reponsequestion_b',
            old_name='question_b',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='reponsequestion_m',
            old_name='question_b',
            new_name='question',
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('auteur', 'suffrage')},
        ),
    ]
