# Generated by Django 2.2.24 on 2021-11-25 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0014_auto_20211125_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposition_m',
            name='question_m',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.Question_majoritaire'),
        ),
    ]
