# Generated by Django 2.2.24 on 2021-11-25 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0015_auto_20211125_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reponsequestion_m',
            name='proposition',
        ),
    ]
