# Generated by Django 2.2.24 on 2021-11-25 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0015_auto_20211125_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='reponsequestion_m',
            name='question',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='qqqqqq'),
        ),
    ]
