# Generated by Django 2.2.24 on 2021-11-25 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0016_reponsequestion_m_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reponsequestion_m',
            name='question',
        ),
    ]
