# Generated by Django 2.2.24 on 2021-11-25 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0017_remove_reponsequestion_m_question'),
    ]

    operations = [
    ]
