# Generated by Django 2.2.24 on 2021-11-25 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0018_reponsequestion_m_question_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reponsequestion_m',
            name='question_id',
        ),
    ]
