# Generated by Django 2.1.7 on 2019-03-05 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190305_2322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentaire',
            old_name='auteur',
            new_name='auteur_comm',
        ),
    ]
