# Generated by Django 2.1.7 on 2019-04-01 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190401_2024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentaireprojet',
            old_name='article',
            new_name='projet',
        ),
    ]
