# Generated by Django 2.1.7 on 2019-04-03 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190403_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='estPublic',
            field=models.BooleanField(default=False, verbose_name='Public (cochez) ou Interne (décochez) [réservé aux membres permacat]'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='estPublic',
            field=models.BooleanField(default=False, verbose_name='Public (cochez) ou Interne (décochez) [réservé aux membres permacat]'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de Modification'),
        ),
    ]
