# Generated by Django 2.1.7 on 2019-04-03 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190403_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de Modification'),
        ),
    ]
