# Generated by Django 2.1.3 on 2019-04-06 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190403_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='date_fichier',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='projet',
            name='fichier_projet',
            field=models.FileField(blank=True, default=None, null=True, upload_to='projets/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='projet',
            name='statut',
            field=models.CharField(choices=[('prop', 'Proposition'), ('AGO', "Soumis à l'AGO"), ('vote', 'Soumis au vote'), ('accep', 'Accepté'), ('refus', 'Refusé')], default='prop', max_length=5, verbose_name='statut'),
        ),
    ]
