# Generated by Django 2.1.3 on 2019-04-04 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190403_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentaire',
            name='titre',
        ),
        migrations.RemoveField(
            model_name='commentaireprojet',
            name='titre',
        ),
    ]
