# Generated by Django 2.1.3 on 2019-04-04 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190404_2053'),
    ]

    operations = [
    ]
