# Generated by Django 2.1.3 on 2019-04-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190406_2145'),
    ]

    operations = [
    ]
