# Generated by Django 2.1.3 on 2019-04-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190406_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date_dernierMessage',
            field=models.DateTimeField(auto_now=True, verbose_name='Date du dernier message'),
        ),
        migrations.AddField(
            model_name='article',
            name='dernierMessage',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='projet',
            name='date_dernierMessage',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de Modification'),
        ),
        migrations.AddField(
            model_name='projet',
            name='dernierMessage',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
