# Generated by Django 2.1.3 on 2019-04-04 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190404_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='coresponsable',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='projet',
            name='date_modification',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de dernière modification'),
        ),
        migrations.AddField(
            model_name='projet',
            name='lien_document',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='projet',
            name='lien_vote',
            field=models.URLField(blank=True, null=True),
        ),
    ]
