# Generated by Django 2.1.3 on 2019-04-04 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190404_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='lien_document',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='Lien vers un document explicatif'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='lien_vote',
            field=models.URLField(blank=True, null=True, verbose_name='Lien vers le vote (balotilo.org)'),
        ),
    ]
