# Generated by Django 2.1.3 on 2019-04-08 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190408_1313'),
    ]

    operations = [
    ]
