# Generated by Django 2.1.3 on 2019-04-06 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20190404_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='categorie',
            field=models.CharField(choices=[('Part', 'Participation à un évènement'), ('AGO', "Organisation d'une AGO"), ('Projlong', 'Projet a long terme'), ('Projcourt', 'Projet a court terme')], default='Part', max_length=10, verbose_name='categorie'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='lien_document',
            field=models.URLField(blank=True, default='', null=True, verbose_name='Lien vers un document explicatif (en ligne)'),
        ),
    ]
