# Generated by Django 2.1.3 on 2019-04-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20190409_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='contenu',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='estPublic',
            field=models.BooleanField(default=False, verbose_name='Public ou réservé aux membres permacat'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='contenu',
            field=models.TextField(null=True),
        ),
    ]
