# Generated by Django 2.1.3 on 2019-04-06 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20190406_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='fichier',
            field=models.FileField(blank=True, default=None, null=True, upload_to='projets/%Y/%m/'),
        ),
    ]
