# Generated by Django 2.1.3 on 2019-04-06 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_projet_fichier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projet',
            old_name='fichier',
            new_name='fichier_projet',
        ),
    ]
