# Generated by Django 2.1.3 on 2019-04-10 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20190409_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='estArchive',
            field=models.BooleanField(default=False, verbose_name="Archiver l'article"),
        ),
        migrations.AlterField(
            model_name='projet',
            name='estArchive',
            field=models.BooleanField(default=False, verbose_name='Archiver le projet'),
        ),
    ]
