# Generated by Django 2.1.3 on 2019-04-24 20:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_article_estmodifiable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='categorie',
            field=models.CharField(choices=[('Annonce', 'Annonce'), ('Agenda', 'Agenda'), ('Rencontre', 'Rencontre'), ('Entraide', 'Entraide'), ('Chantier', 'Chantier participatif'), ('Jardinage', 'Jardinage'), ('Recette', 'Recette'), ('Bricolage', 'Bricolage'), ('Culture', 'Culture'), ('Bon_plan', 'Bon plan'), ('Point', 'Point de vue'), ('Autre', 'Autre')], default='Annonce', max_length=30, verbose_name='categorie'),
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-date_creation',)},
        ),
        migrations.AlterModelOptions(
            name='projet',
            options={'ordering': ('-date_creation',)},
        ),
        migrations.RemoveField(
            model_name='article',
            name='date',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='date',
        ),
        migrations.AddField(
            model_name='article',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de parution'),
        ),
        migrations.AddField(
            model_name='article',
            name='date_modification',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de modification'),
        ),
        migrations.AddField(
            model_name='projet',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de parution'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='coresponsable',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Référent du projet'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='date_modification',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de modification'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='statut',
            field=models.CharField(choices=[('prop', 'Proposition de projet'), ('AGO', "Fiche prpojet soumise à l'AGO"), ('vote', 'Soumis au vote'), ('accep', "Accepté par l'association"), ('refus', "Refusé par l'association")], default='prop', max_length=5, verbose_name='statut'),
        ),
    ]
