# Generated by Django 2.1.3 on 2019-05-30 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20190517_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='categorie',
            field=models.CharField(choices=[('Annonce', 'Annonce'), ('Administratif', 'Administratif'), ('Agenda', 'Agenda'), ('Entraide', 'Entraide'), ('Chantier', 'Chantier participatif'), ('Jardinage', 'Jardinage'), ('Recette', 'Recette'), ('Bricolage', 'Bricolage'), ('Culture', 'Culture'), ('Bon_plan', 'Bon plan'), ('Point', 'Point de vue'), ('Autre', 'Autre')], default='Annonce', max_length=30, verbose_name='categorie'),
        ),
    ]
