# Generated by Django 2.1.11 on 2019-10-05 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20191002_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='categorie',
            field=models.CharField(choices=[('Annonce', 'Annonce'), ('Administratif', 'Administratif'), ('Agenda', 'Agenda'), ('Entraide', 'Entraide'), ('Chantier', 'Chantier participatif'), ('Jardinage', 'Jardinage'), ('Recette', 'Recette'), ('Bricolage', 'Bricolage'), ('Documentation', 'Documentation'), ('Projet', 'Projet'), ('Point', 'Point de vue'), ('Ecovillage', 'Ecovillage'), ('Serre', 'Serre collective'), ('Altermarché', 'Altermarché'), ('Autre', 'Autre')], default='Annonce', max_length=30, verbose_name='categorie'),
        ),
    ]
