# Generated by Django 2.2.8 on 2020-01-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20191210_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de fin'),
        ),
        migrations.AddField(
            model_name='article',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de début'),
        ),
        migrations.AddField(
            model_name='projet',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de fin'),
        ),
        migrations.AddField(
            model_name='projet',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de début'),
        ),
    ]
