# Generated by Django 2.2.8 on 2020-01-05 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20200105_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaireprojet',
            name='commentaire',
            field=models.TextField(blank=True),
        ),
    ]
