# Generated by Django 2.2.8 on 2020-01-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20200106_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='end_time',
            field=models.DateTimeField(blank=True, help_text='jj/mm/année', null=True, verbose_name="Date de fin (optionnel, pour affichage dans l'agenda)"),
        ),
        migrations.AlterField(
            model_name='article',
            name='start_time',
            field=models.DateTimeField(blank=True, help_text='jj/mm/année', null=True, verbose_name="Date de début (optionnel, affichage dans l'agenda)"),
        ),
        migrations.AlterField(
            model_name='projet',
            name='end_time',
            field=models.DateTimeField(blank=True, help_text='jj/mm/année', null=True, verbose_name="Date de fin (optionnel, pour affichage dans l'agenda)"),
        ),
        migrations.AlterField(
            model_name='projet',
            name='start_time',
            field=models.DateTimeField(blank=True, help_text='jj/mm/année', null=True, verbose_name="Date de début (optionnel, pour affichage dans l'agenda)"),
        ),
    ]
