# Generated by Django 2.1.11 on 2020-01-22 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20200110_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='categorie',
            field=models.CharField(choices=[('Altermarché', 'Altermarché'), ('Annonce', 'Annonce'), ('Administratif', 'Administratif'), ('Agenda', 'Agenda'), ('Bricolage', 'Bricolage'), ('Chantier', 'Chantier participatif'), ('Documentation', 'Documentation'), ('Ecovillage', 'Ecovillage'), ('Entraide', 'Entraide'), ('Permaculture', 'Permaculture'), ('Point', 'Point de vue'), ('Projet', 'Projet'), ('Recette', 'Recette'), ('Serre', 'Serre collective'), ('Autre', 'Autre')], default='Annonce', max_length=30, verbose_name='categorie'),
        ),
    ]
