# Generated by Django 2.2.8 on 2020-02-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_evenement_titre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='titre',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name="Titre de l'événement (si laissé vide, ce sera le titre de l'article)"),
        ),
    ]
