# Generated by Django 2.2.8 on 2020-03-04 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_auto_20200217_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='categorie',
            field=models.CharField(choices=[('Altermarché', 'Altermarché'), ('Annonce', 'Annonce'), ('Administratif', 'Administratif'), ('Agenda', 'Agenda'), ('Jardi', 'Jardi per tots'), ('Chantier', 'Chantier participatif'), ('Documentation', 'Documentation'), ('Ecovillage', 'Ecovillage'), ('Entraide', 'Entraide'), ('Permaculture', 'Permaculture'), ('Point', 'Point de vue'), ('KitPerma', 'Kit Perma Ecole'), ('Recette', 'Recette'), ('Serre', 'Serre collective'), ('Autre', 'Autre')], default='Annonce', max_length=30, verbose_name='categorie'),
        ),
    ]
