# Generated by Django 2.2.8 on 2020-06-08 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_auto_20200304_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='categorie',
            field=models.CharField(choices=[('Altermarché', 'Altermarché'), ('Annonce', 'Annonce'), ('Administratif', 'Administratif'), ('Agenda', 'Agenda'), ('Jardi', 'Jardi per tots'), ('Chantier', 'Chantier participatif'), ('Documentation', 'Documentation'), ('Ecovillage', 'Ecovillage'), ('Point', 'Point de vue'), ('KitPerma', 'Kit Perma Ecole'), ('Recette', 'Recette'), ('Jardin', 'Jardins partagés'), ('Autre', 'Autre')], default='Annonce', max_length=30, verbose_name='categorie'),
        ),
    ]
