# Generated by Django 2.2.8 on 2020-06-08 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_auto_20200608_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_dernierMessage',
            field=models.DateTimeField(verbose_name='Date du dernier message'),
        ),
    ]
