# Generated by Django 2.2.8 on 2020-06-11 21:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_auto_20200609_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_dernierMessage',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date du dernier message'),
        ),
    ]
