# Generated by Django 2.2.8 on 2020-06-12 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_auto_20200611_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='statut',
            field=models.CharField(choices=[('prop', 'Proposition de projet'), ('AGO', "Fiche projet soumise à l'AGO"), ('vote', 'Soumis au vote'), ('accep', "Accepté par l'association"), ('refus', "Refusé par l'association")], default='prop', max_length=5, verbose_name='statut'),
        ),
    ]
