# Generated by Django 2.2.13 on 2020-08-25 19:52

from django.db import migrations, models
import django.db.models.deletion
from bourseLibre.models import Asso

def combine_names(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    article = apps.get_model('blog', 'Article')
    assos = apps.get_model('bourseLibre', 'Asso')
    asso_public, created = assos.objects.get_or_create(nom='Public')
    asso_permacat, created = assos.objects.get_or_create(nom='Permacat')
    for art in article.objects.all():
        if art.estPublic:
            art.asso = asso_public
        else:
            art.asso = asso_permacat
        art.save()
    proj = apps.get_model('blog', 'Projet')
    for prod in proj.objects.all():
        if prod.estPublic:
            prod.asso = asso_public
        else:
            prod.asso = asso_permacat
        prod.save()


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0033_auto_20200825_2014'),
        ('blog', '0035_auto_20200613_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='asso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bourseLibre.Asso'),
        ),
        migrations.AddField(
            model_name='projet',
            name='asso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bourseLibre.Asso'),
        ),
        migrations.RunPython(combine_names, ),
    ]
