# Generated by Django 2.2.13 on 2020-09-17 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0036_auto_20200825_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='categorie',
            field=models.CharField(choices=[('Altermarché', 'Altermarché'), ('Annonce', 'Annonce'), ('Administratif', 'Administratif'), ('Agenda', 'Agenda'), ('Chantier', 'Chantier participatif'), ('Documentation', 'Documentation'), ('Ecovillage', 'Ecovillage'), ('Point', 'Point de vue'), ('Recette', 'Recette'), ('Jardin', 'Jardins partagés'), ('Autre', 'Autre')], default='Annonce', max_length=30, verbose_name='categorie'),
        ),
    ]
