# Generated by Django 2.2.13 on 2020-09-26 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0038_evenementacceuil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evenementacceuil',
            old_name='start_time',
            new_name='date',
        ),
        migrations.AlterUniqueTogether(
            name='evenementacceuil',
            unique_together={('article', 'date')},
        ),
    ]
