# Generated by Django 2.2.13 on 2021-03-12 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0042_auto_20210222_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='categorie',
            field=models.CharField(choices=[('Annonce', 'Annonce'), ('Administratif', 'Administratif'), ('Agenda', 'Agenda'), ('Chantier', 'Chantiers participatifs/Ateliers collectifs'), ('Documentation', 'Documentation'), ('Point', 'Points de vue'), ('Recette', 'Recettes'), ('BonPlan', 'Bons Plans / achats groupés'), ('Divers', 'Divers'), ('Altermarché', 'Altermarché'), ('Ecovillage', 'Ecovillage'), ('Jardin', 'Jardins partagés')], default='Annonce', max_length=30, verbose_name='categorie'),
        ),
    ]
