# Generated by Django 2.2.13 on 2021-03-12 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0043_auto_20210312_0158'),
        ('blog', '0044_auto_20210312_1230'),
    ]

    operations = [
    ]
