# Generated by Django 2.2.13 on 2021-03-12 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0045_merge_20210312_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='categorie',
            field=models.CharField(choices=[('Annonce', 'Annonces'), ('Administratif', 'Administratif'), ('Agenda', 'Agenda'), ('Chantier', 'Chantiers participatifs/Ateliers collectifs'), ('Documentation', 'Documentation'), ('Point', 'Points de vue'), ('Recette', 'Recettes'), ('BonPlan', 'Bons Plans / achats groupés'), ('Divers', 'Divers'), ('Altermarché', 'Altermarché'), ('Ecovillage', 'Ecovillage'), ('Jardin', 'Jardins partagés')], default='Annonce', max_length=30, verbose_name='categorie'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='statut',
            field=models.CharField(choices=[('prop', 'Proposition de projet'), ('AGO', "Fiche projet soumise à l'AGO"), ('accep', "Accepté par l'association"), ('refus', "Refusé par l'association")], default='prop', max_length=5, verbose_name='statut'),
        ),
    ]
