# Generated by Django 2.2.13 on 2021-03-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0045_auto_20210312_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_dernierMessage',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date du dernier message'),
        ),
    ]
