# Generated by Django 2.2.13 on 2021-03-12 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0047_auto_20210312_2237'),
        ('blog', '0045_auto_20210312_2234'),
    ]

    operations = [
    ]
