# Generated by Django 2.2.13 on 2021-04-06 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0048_auto_20210406_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='date_dernierMessage',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de Modification'),
        ),
    ]
