# Generated by Django 2.2.13 on 2021-03-15 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0046_auto_20210315_1156'),
        ('blog', '0048_merge_20210312_2238'),
    ]

    operations = [
    ]
