# Generated by Django 2.2.13 on 2021-03-15 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0047_auto_20210315_1208'),
        ('blog', '0049_merge_20210315_1201'),
    ]

    operations = [
    ]
