# Generated by Django 2.2.13 on 2021-04-06 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0049_auto_20210406_2056'),
        ('blog', '0050_merge_20210315_1219'),
    ]

    operations = [
    ]
