# Generated by Django 2.2.20 on 2021-05-26 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0052_auto_20210526_1946'),
        ('blog', '0051_merge_20210406_2132'),
    ]

    operations = [
    ]
