# Generated by Django 2.2.20 on 2021-05-26 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0053_merge_20210526_2237'),
        ('blog', '0053_auto_20210526_2232'),
    ]

    operations = [
    ]
