# Generated by Django 2.2.24 on 2021-06-19 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0056_article_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='photologue.Album'),
        ),
    ]
