# Generated by Django 2.2.24 on 2021-07-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0059_auto_20210726_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_modification',
            field=models.DateTimeField(null=True, verbose_name='Date de modification'),
        ),
    ]
