# Generated by Django 2.2.24 on 2021-08-15 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0062_adressearticle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='categorie',
            field=models.CharField(choices=[('Annonce', 'Annonce'), ('Administratif', 'Administratif'), ('Agenda', 'Agenda'), ('Chantier', 'Atelier/Chantier participatif'), ('Documentation', 'Documentation'), ('covoit', 'Covoiturage'), ('Point', 'Point de vue'), ('Recette', 'Recette'), ('BonPlan', 'Bon Plan / achat groupé'), ('Divers', 'Divers'), ('Altermarché', 'Altermarché'), ('Ecovillage', 'Ecovillage'), ('Jardin', 'Jardins partagés')], default='Annonce', max_length=30, verbose_name='categorie'),
        ),
    ]
