# Generated by Django 2.2.24 on 2021-09-06 13:52

from django.db import migrations, models
import django.db.models.deletion


def ajouterDiscussionCommentaires(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    discu = apps.get_model('blog', 'Discussion')
    comments = apps.get_model('blog', 'Commentaire')
    articles = apps.get_model('blog', 'Article')
    for art in articles.objects.all():
        discussion, created = discu.objects.get_or_create(article=art, titre="Discussion Générale")
        for comment in comments.objects.filter(article=art):
            comment.discussion = discussion
            comment.save()

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0066_auto_20210905_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=32)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Article')),
            ],
        ),
        migrations.AddField(
            model_name='commentaire',
            name='discussion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Discussion'),
        ),
        migrations.RunPython(ajouterDiscussionCommentaires, ),
    ]
