# Generated by Django 2.2.24 on 2021-09-06 13:59

from django.db import migrations, models
from django.utils.text import slugify

def ajouterDiscussionSlug(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    discu = apps.get_model('blog', 'Discussion')
    for disc in discu.objects.filter():
        disc.slug = slugify(disc.titre)
        disc.save()

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0067_discussion'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='slug',
            field=models.SlugField(default=None, max_length=100, null=True),
            preserve_default=False,
        ),
        migrations.RunPython(ajouterDiscussionSlug, ),
    ]
