# Generated by Django 2.2.24 on 2021-09-07 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from bourseLibre.models import Profil
from blog.models import Evenement

def ajouterAuteurEvenement(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    profil = Profil.objects.get(username='Eloi')
    for disc in Evenement.objects.filter():
        disc.auteur = profil
        disc.save()

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0069_auto_20210907_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='auteur',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.RunPython(ajouterAuteurEvenement, ),
    ]
