# Generated by Django 2.2.24 on 2021-09-07 15:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0071_auto_20210907_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, max_length=32),
        ),
    ]
