# Generated by Django 2.2.24 on 2021-09-07 20:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0073_auto_20210907_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='end_time',
            field=models.DateField(blank=True, help_text='jj/mm/année', null=True, verbose_name="Date de fin (optionnel, pour affichage dans l'agenda)"),
        ),
        migrations.AlterField(
            model_name='article',
            name='start_time',
            field=models.DateField(blank=True, help_text='jj/mm/année', null=True, verbose_name="Date de l'évenement (pour affichage dans l'agenda) - date de début si l'événement a lieu sur plusieurs jours "),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='end_time',
            field=models.DateField(blank=True, help_text='jj/mm/année', null=True, verbose_name='Date de fin (optionnel pour un evenement sur plusieurs jours)'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='start_time',
            field=models.DateField(default=django.utils.timezone.now, help_text='jj/mm/année', verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='end_time',
            field=models.DateField(blank=True, help_text='jj/mm/année', null=True, verbose_name="Date de fin (optionnel, pour affichage dans l'agenda)"),
        ),
        migrations.AlterField(
            model_name='projet',
            name='start_time',
            field=models.DateField(blank=True, help_text='jj/mm/année', null=True, verbose_name="Date de début (optionnel, pour affichage dans l'agenda)"),
        ),
    ]
