# Generated by Django 2.2.24 on 2021-09-07 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0074_auto_20210907_2226'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='evenement',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='evenementacceuil',
            unique_together=set(),
        ),
    ]
