# Generated by Django 2.2.24 on 2021-09-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0075_auto_20210907_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='start_time',
            field=models.DateField(blank=True, help_text='jj/mm/année', null=True, verbose_name="Date de l'événement (pour affichage dans l'agenda) - date de début si l'événement a lieu sur plusieurs jours "),
        ),
    ]
