# Generated by Django 2.2.24 on 2021-09-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0076_auto_20210913_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='categorie',
            field=models.CharField(choices=[('Annonce', 'Annonce'), ('Administratif', 'Organisation'), ('Agenda', 'Agenda'), ('Chantier', 'Atelier/Chantier participatif'), ('Documentation', 'Documentation'), ('covoit', 'Covoiturage'), ('Point', 'Idée / Point de vue'), ('Recette', 'Recette'), ('BonPlan', 'Bon Plan / achat groupé'), ('Divers', 'Divers'), ('groupe1', 'Groupe de Perpignan'), ('groupe2', 'Groupe des Albères'), ('groupe3', 'Groupe des Aspres'), ('groupe4', 'Groupe du Vallespir'), ('groupe5', 'Groupe du Ribéral'), ('groupe6', 'Groupe du Conflent'), ('groupe6', 'Groupe de la côte'), ('Altermarché', 'Altermarché'), ('Ecovillage', 'Ecovillage'), ('Jardin', 'Jardins partagés')], default='Annonce', max_length=30, verbose_name='categorie'),
        ),
    ]
