# Generated by Django 2.2.27 on 2022-03-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0081_auto_20220224_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='estEpingle',
            field=models.BooleanField(default=False, verbose_name='Article épinglé'),
        ),
    ]
