# Generated by Django 2.2.28 on 2022-08-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0077_auto_20220817_2251'),
        ('blog', '0090_auto_20220725_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='partages',
            field=models.ManyToManyField(related_name='asso_partages', to='bourseLibre.Asso'),
        ),
    ]
