# Generated by Django 2.2.28 on 2022-08-19 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0091_article_partages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='partages',
            new_name='partagesAsso',
        ),
    ]
