# Generated by Django 2.2.28 on 2022-08-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0092_auto_20220819_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='partagesAsso',
            field=models.ManyToManyField(blank=True, related_name='asso_partages', to='bourseLibre.Asso', verbose_name='Partagé avec :'),
        ),
    ]
