# Generated by Django 2.2.28 on 2022-08-21 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0093_auto_20220820_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='start_time',
            field=models.DateField(blank=True, help_text='jj/mm/année', null=True, verbose_name="Date de l'événement (pour apparaitre sur l'agenda, sinon vous pourrez ajouter des évènements depuis l'article) "),
        ),
        migrations.AlterField(
            model_name='projet',
            name='end_time',
            field=models.DateField(blank=True, help_text='jj/mm/année', null=True, verbose_name="Date de fin (optionnel, pour apparaitre dans l'agenda)"),
        ),
        migrations.AlterField(
            model_name='projet',
            name='start_time',
            field=models.DateField(blank=True, help_text='jj/mm/année', null=True, verbose_name="Date de début (optionnel, pour apparaitre dans l'agenda)"),
        ),
    ]
