# Generated by Django 2.2.28 on 2022-11-19 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0094_auto_20220821_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='FicheProjet',
            fields=[
                ('projet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='blog.Projet')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('raison', models.TextField(blank=True, null=True, verbose_name="Raison d'Etre du projet")),
                ('pourquoi_contexte', models.TextField(blank=True, null=True, verbose_name='Pourquoi ? Le contexte')),
                ('pourquoi_motivation', models.TextField(blank=True, null=True, verbose_name='Pourquoi ? Les motivations')),
                ('pourquoi_objectifs', models.TextField(blank=True, null=True, verbose_name='Pourquoi ? Les objectifs')),
                ('pour_qui', models.TextField(blank=True, null=True, verbose_name='Pour qui ? Le public')),
                ('par_qui', models.TextField(blank=True, null=True, verbose_name='Par qui ? Les acteurs')),
                ('avec_qui', models.TextField(blank=True, null=True, verbose_name='Par qui ? Les partenaires')),
                ('ou', models.TextField(blank=True, null=True, verbose_name='Où ?')),
                ('quand', models.TextField(blank=True, null=True, verbose_name='Début ? La périodicité')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment ? La méthodologie')),
                ('combien', models.TextField(blank=True, null=True, verbose_name='Combien ? Le budget prévisionnel')),
            ],
            options={
                'ordering': ('-date_creation',),
            },
        ),
    ]
