# Generated by Django 2.1.11 on 2019-11-04 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentairefiche',
            old_name='article',
            new_name='fiche',
        ),
    ]
