# Generated by Django 2.1.11 on 2019-11-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0003_auto_20191104_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atelier',
            name='age',
            field=models.CharField(choices=[('0', '3-6 ans'), ('1', '7-11 ans'), ('2', '12 ans et plus')], default='0', max_length=30, verbose_name='age'),
        ),
        migrations.AlterField(
            model_name='atelier',
            name='difficulte',
            field=models.CharField(choices=[('0', 'facile'), ('1', 'moyen'), ('2', 'difficile')], default='0', max_length=30, verbose_name='difficulté'),
        ),
    ]
