# Generated by Django 2.1.11 on 2019-11-04 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0004_auto_20191104_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atelier',
            name='age',
            field=models.CharField(choices=[('0', '3-6 ans'), ('1', '7-11 ans'), ('2', '12 ans et plus'), ('3', '3-11ans'), ('2', '12 ans et plus')], default='0', max_length=30, verbose_name='age'),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='categorie',
            field=models.CharField(choices=[('0', 'Bases de la permaculture'), ('1', 'Conception du jardin'), ('2', 'Réalisation du jardin'), ('3', 'Récolter')], default='0', max_length=30, verbose_name='categorie'),
        ),
    ]
