# Generated by Django 2.1.11 on 2019-11-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0006_auto_20191104_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiche',
            name='en_savoir_plus',
            field=models.TextField(blank=True, null=True),
        ),
    ]
