# Generated by Django 2.1.11 on 2019-11-05 11:12

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('fiches', '0007_auto_20191105_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiche',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
