# Generated by Django 2.1.11 on 2019-11-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0009_auto_20191107_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiche',
            name='objectif',
            field=models.TextField(blank=True, null=True),
        ),
    ]
