# Generated by Django 2.1.11 on 2019-11-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0010_fiche_objectif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atelier',
            name='age',
            field=models.CharField(choices=[('0', '3-6 ans'), ('1', '7-11 ans'), ('2', '12 ans et plus'), ('3', '3-11ans'), ('4', 'Tout public')], default='0', max_length=30, verbose_name='age'),
        ),
    ]
