# Generated by Django 2.1.11 on 2019-11-07 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0011_auto_20191107_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fiche',
            name='objectif',
        ),
    ]
