# Generated by Django 2.1.11 on 2019-11-07 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0012_remove_fiche_objectif'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiche',
            name='objectif',
            field=models.TextField(blank=True, null=True),
        ),
    ]
