# Generated by Django 2.1.11 on 2019-11-08 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0014_fiche_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atelier',
            name='budget',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3')], default='0', max_length=30, verbose_name='budget'),
        ),
        migrations.RemoveField(
            model_name='atelier',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='fiche',
            name='slug',
        ),
    ]
