# Generated by Django 2.1.11 on 2019-11-08 20:13

from django.db import migrations, models
import uuid
from django.utils.text import slugify
import itertools
from fiches.models import Fiche, Atelier  #where app == tango_app_name

class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0015_auto_20191108_2105'),
    ]

    def gen_uuid(apps, schema_editor):
        max_length = Fiche._meta.get_field('slug').max_length
        for row in Fiche.objects.all():
            orig = slugify(row.titre)[:max_length]
            if not orig or Fiche.objects.filter(slug=row.slug).exists():
                orig = uuid.uuid4()[:max_length]
            row.slug = orig
            row.save()

        max_length = Atelier._meta.get_field('slug').max_length
        for row in Atelier.objects.all():
            orig = slugify(row.titre)[:max_length]
            if  not orig or Fiche.objects.filter(slug=row.slug).exists():
                orig = uuid.uuid4()[:max_length]
            row.slug = orig
            row.save()

    operations = [

        migrations.RemoveField(
            model_name='fiche',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='atelier',
            name='slug',
        ),
        migrations.AddField(
            model_name='fiche',
            name='slug',
            field=models.SlugField(default=uuid.uuid4),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='atelier',
            name='slug',
            field=models.SlugField(default=uuid.uuid4),
            preserve_default=True,
        ),

        migrations.RunPython(gen_uuid),

        migrations.AlterField(
            model_name='fiche',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='atelier',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
