# Generated by Django 2.1.11 on 2019-11-08 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0015_auto_20191108_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atelier',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='fiche',
            name='slug',
        ),
    ]
