# Generated by Django 2.1.11 on 2019-11-08 21:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0016_auto_20191108_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='atelier',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='fiche',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, max_length=100, unique=True),
        ),
    ]
