# Generated by Django 2.1.11 on 2019-11-08 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiches', '0016_auto_20191108_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atelier',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
