# Generated by Django 2.2.8 on 2020-02-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_evenement'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='estPublic',
            field=models.BooleanField(default=False, verbose_name='Public ou réservé aux membres permacat'),
        ),
    ]
