# Generated by Django 2.2.8 on 2020-02-17 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_evenement_estpublic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='titre',
            field=models.CharField(max_length=100),
        ),
    ]
