# Generated by Django 2.2.8 on 2020-02-17 11:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_auto_20200217_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='jj/mm/année', verbose_name='Date de début '),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='titre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
