# Generated by Django 2.2.8 on 2020-02-17 12:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_auto_20200217_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evenement',
            name='estPublic',
        ),
        migrations.RemoveField(
            model_name='evenement',
            name='titre',
        ),
        migrations.AlterField(
            model_name='evenement',
            name='end_time',
            field=models.DateTimeField(blank=True, help_text='jj/mm/année', null=True, verbose_name='Date de fin (optionnel)'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='jj/mm/annéeend_t', verbose_name='Date de début '),
        ),
    ]
