# Generated by Django 2.2.8 on 2020-02-17 12:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_auto_20200217_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='article',
            field=models.ForeignKey(help_text="L'evenement doit etre associé à un article existant (sinon créez un article avec une date)", on_delete=django.db.models.deletion.CASCADE, to='blog.Article'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='jj/mm/année', verbose_name='Date de début '),
        ),
        migrations.AlterUniqueTogether(
            name='evenement',
            unique_together={('article', 'start_time')},
        ),
    ]
