# Generated by Django 2.1.7 on 2019-03-12 15:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0002_auto_20190307_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit_aliment',
            name='etat',
        ),
        migrations.RemoveField(
            model_name='produit_objet',
            name='etat',
        ),
        migrations.RemoveField(
            model_name='produit_service',
            name='etat',
        ),
        migrations.RemoveField(
            model_name='produit_vegetal',
            name='etat',
        ),
        migrations.AlterField(
            model_name='produit',
            name='date_expiration',
            field=models.DateField(blank=True, default=datetime.date(2019, 4, 2), null=True, verbose_name='Expire le : (jj/mm/an)'),
        ),
        migrations.AlterField(
            model_name='produit_vegetal',
            name='souscategorie',
            field=models.CharField(choices=[('graines', 'graines'), ('fleurs', 'fleurs'), ('plantes', 'plantes'), ('jeunes plans', 'jeunes plans'), ('purins', 'purins'), ('autre', 'autre')], default='g', max_length=20),
        ),
    ]
