# Generated by Django 2.1.7 on 2019-03-14 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0002_auto_20190314_1829'),
    ]

    operations = [
    ]
