# Generated by Django 2.1.7 on 2019-03-22 00:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0003_auto_20190314_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageGeneral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='produit_objet',
            name='souscategorie',
            field=models.CharField(choices=[('jardinage', 'jardinage'), ('outillage', 'outillage'), ('vehicule', 'vehicule'), ('multimedia', 'multimedia'), ('mobilier', 'mobilier'), ('construction', 'construction'), ('instrument', 'instrument'), ('autre', 'autre')], default='j', max_length=20),
        ),
        migrations.AlterField(
            model_name='produit_service',
            name='souscategorie',
            field=models.CharField(choices=[('jardinage', 'jardinage'), ('éducation', 'éducation'), ('santé', 'santé'), ('bricolage', 'bricolage'), ('informatique', 'informatique'), ('cuisine', 'cuisine'), ('batiment', 'batiment'), ('mécanique', 'mécanique'), ('autre', 'autre')], default='j', max_length=20),
        ),
        migrations.AlterField(
            model_name='produit_vegetal',
            name='souscategorie',
            field=models.CharField(choices=[('plantes', 'plantes'), ('graines', 'graines'), ('fleurs', 'fleurs'), ('jeunes plants', 'jeunes plants'), ('purins', 'purins'), ('autre', 'autre')], default='p', max_length=20),
        ),
    ]
