# Generated by Django 2.1.7 on 2019-03-12 15:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0003_auto_20190312_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='adresse',
            name='commune',
            field=models.CharField(blank=True, default='Perpignan', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='date_debut',
            field=models.DateField(blank=True, null=True, verbose_name='Débute le : (mm/jj/an)'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='date_expiration',
            field=models.DateField(blank=True, null=True, verbose_name='Expire le : (jj/mm/an)'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='stock_initial',
            field=models.FloatField(max_length=250, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantité disponible'),
        ),
    ]
