# Generated by Django 2.1.7 on 2019-04-01 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0004_auto_20190322_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='accepter_conditions',
            field=models.BooleanField(default=False, verbose_name="J'accepte les conditions d'utilisation du site"),
        ),
        migrations.AddField(
            model_name='profil',
            name='membre_permacat',
            field=models.BooleanField(default=False, verbose_name="Je souhaite adhérer à l'association 'PermaCat'"),
        ),
        migrations.AlterField(
            model_name='produit',
            name='date_debut',
            field=models.DateField(blank=True, null=True, verbose_name='Débute le : (jj/mm/an)'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='site_web',
            field=models.URLField(blank=True, null=True),
        ),
    ]
