# Generated by Django 2.1.7 on 2019-04-01 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0004_auto_20190322_0027'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageGeneral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='profil',
            name='accepter_conditions',
            field=models.BooleanField(default=False, verbose_name="J'accepte les conditions d'utilisation du site"),
        ),
        migrations.AddField(
            model_name='profil',
            name='membre_permacat',
            field=models.BooleanField(default=False, verbose_name="Je souhaite adhérer à l'association 'PermaCat'"),
        ),
        migrations.AlterField(
            model_name='produit',
            name='date_debut',
            field=models.DateField(blank=True, null=True, verbose_name='Débute le : (jj/mm/an)'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='site_web',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='messagegeneral',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
