# Generated by Django 2.1.7 on 2019-04-03 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0005_auto_20190401_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='membre_permacat',
        ),
        migrations.AddField(
            model_name='profil',
            name='statut_adhesion',
            field=models.IntegerField(choices=[('', '-----------'), (0, "Je souhaite devenir membre de l'association 'PermaCat' et utiliser le site"), (1, "Je souhaite utiliser le site, mais ne pas devenir membre de l'association"), (2, "Je suis déjà membre de l'association")], default='0'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='accepter_conditions',
            field=models.BooleanField(default=False, verbose_name="J'ai lu et j'accepte les conditions d'utilisation du site"),
        ),
        migrations.AlterField(
            model_name='profil',
            name='competences',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='inscrit_newsletter',
            field=models.BooleanField(default=False, verbose_name="J'accepte de recevoir des emails de Permacat"),
        ),
        migrations.AlterField(
            model_name='profil',
            name='pseudo_june',
            field=models.CharField(default=None, max_length=150, null=True, unique=True, verbose_name='pseudo Monnaie Libre'),
        ),
    ]
