# Generated by Django 2.1.7 on 2019-04-03 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0006_auto_20190403_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='pseudo_june',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='pseudo Monnaie Libre'),
        ),
    ]
