# Generated by Django 2.1.7 on 2019-04-03 19:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0007_auto_20190403_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='date_dernierMessage',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de Modification'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='estPublique',
            field=models.BooleanField(default=False, verbose_name='Publique (cochez) ou Interne (décochez) [réservé aux membres permacat]'),
        ),
    ]
