# Generated by Django 2.1.7 on 2019-04-03 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0008_auto_20190403_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='date_dernierMessage',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de Modification'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4),
        ),
    ]
