# Generated by Django 2.1.7 on 2019-04-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0010_auto_20190404_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit_aliment',
            name='souscategorie',
            field=models.CharField(choices=[('legumes', 'legumes'), ('fruits', 'fruits'), ('aromates', 'aromates'), ('champignons', 'champignons'), ('boisson', 'boisson'), ('herbes', 'herbes'), ('condiments', 'condiments'), ('viande', 'viande'), ('poisson', 'poisson'), ('boulangerie', 'boulangerie'), ('patisserie', 'patisserie'), ('autre', 'autre')], default='l', max_length=20),
        ),
    ]
