# Generated by Django 2.1.3 on 2019-04-08 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0012_profil_accepter_annuaire'),
    ]

    operations = [
    ]
