# Generated by Django 2.1.3 on 2019-04-08 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0013_conversation_derniermessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='accepter_annuaire',
            field=models.BooleanField(default=True, verbose_name="J'accepte d'apparaitre dans l'annuaire du site et la carte et rend mon profil visible par tous"),
        ),
    ]
