# Generated by Django 2.1.3 on 2019-04-09 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0015_auto_20190409_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='unite_prix',
            field=models.CharField(choices=[('don', 'don'), ('troc', 'troc'), ('pret', 'pret'), ('G1', 'G1'), ('Soudaqui', 'Soudaqui'), ('SEL', 'SEL'), ('JEU', 'JEU'), ('heuresT', 'heuresT'), ('Autre', 'A negocier')], default='lliure', max_length=8, verbose_name='monnaie'),
        ),
    ]
