# Generated by Django 2.1.3 on 2019-04-19 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0018_auto_20190416_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='competences',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='pseudo_june',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='(optionnel) pseudo Monnaie Libre'),
        ),
    ]
