# Generated by Django 2.1.3 on 2019-05-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0019_auto_20190419_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='date_debut',
            field=models.DateField(blank=True, null=True, verbose_name='Débute le (jj/mm/an)'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='date_expiration',
            field=models.DateField(blank=True, null=True, verbose_name='Expire le (jj/mm/an)'),
        ),
    ]
