# Generated by Django 2.1.3 on 2019-05-30 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0020_auto_20190514_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='prix',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=6),
        ),
    ]
