# Generated by Django 2.1.5 on 2019-08-12 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0021_auto_20190530_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suivis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_suivi', models.TextField()),
            ],
        ),
    ]
