# Generated by Django 2.1.11 on 2019-10-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0022_suivis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='unite_prix',
            field=models.CharField(choices=[('don', 'don'), ('troc', 'troc'), ('pret', 'prêt'), ('G1', 'G1'), ('Soudaqui', 'Soudaqui'), ('SEL', 'SEL'), ('JEU', 'JEU'), ('HE', 'heureEntraide'), ('Autre', 'A négocier')], default='lliure', max_length=8, verbose_name='monnaie'),
        ),
    ]
