# Generated by Django 2.1.11 on 2019-12-05 00:24

from django.db import migrations, models
import django.utils.timezone

class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0025_messagegeneralrtg'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='statut_adhesion_rtg',
            field=models.IntegerField(choices=[('', '-----------'), (0, "Je souhaite devenir membre de l'association 'Ramene Ta Graine' et utiliser le site"), (1, "Je souhaite utiliser le site, mais ne pas devenir membre de l'association RTG"), (2, "Je suis déjà membre de l'association Ramene Ta Graine")], default='0'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='statut_adhesion',
            field=models.IntegerField(choices=[('', '-----------'), (0, "Je souhaite devenir membre de l'association 'PermaCat' et utiliser le site"), (1, "Je souhaite utiliser le site, mais ne pas devenir membre de l'association Permacat"), (2, "Je suis déjà membre de l'association Permacat")], default='0'),
        ),
        migrations.AddField(
            model_name='profil',
            name='date_notifications',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de validation des notifications'),
        ),
    ]
