# Generated by Django 2.2.8 on 2020-02-07 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0028_profil_date_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adhesion_permacat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_cotisation', models.DateTimeField(auto_now_add=True, verbose_name='Date de la cotisation')),
                ('montant', models.CharField(blank=True, max_length=50, verbose_name="Montant de l'adhesion")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
