# Generated by Django 2.2.8 on 2020-02-07 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0029_adhesion_permacat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adhesion_permacat',
            name='date_cotisation',
            field=models.DateField(verbose_name='Date de la cotisation'),
        ),
    ]
