# Generated by Django 2.2.8 on 2020-06-13 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0030_auto_20200207_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='is_jardinpartage',
            field=models.BooleanField(default=False, verbose_name='Je suis intéressé.e par les jardins partagés'),
        ),
    ]
