# Generated by Django 2.2.13 on 2020-08-17 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0031_profil_is_jardinpartage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='pseudo_june',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='pseudo Monnaie Libre'),
        ),
    ]
