# Generated by Django 2.2.13 on 2020-08-25 18:14

from django.db import migrations, models
from bourseLibre.models import Asso
import django.db.models.deletion

def combine_names(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    produits = apps.get_model('bourseLibre', 'Produit')
    assos = apps.get_model('bourseLibre', 'Asso')
    asso_public, created = assos.objects.get_or_create(nom='Public')
    asso_permacat, created = assos.objects.get_or_create(nom='Permacat')
    for prod in produits.objects.all():
        if prod.estPublique:
            prod.asso = asso_public
        else:
            prod.asso = asso_permacat
        prod.save()

class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0032_auto_20200818_0019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('abreviation', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('date_inscription', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
            ],
        ),
        migrations.AddField(
            model_name='profil',
            name='adherent_ame',
            field=models.BooleanField(default=False, verbose_name='Je suis adhérent de Animaux Mieux Etre'),
        ),
        migrations.AddField(
            model_name='profil',
            name='adherent_permacat',
            field=models.BooleanField(default=False, verbose_name='Je suis adhérent de Permacat'),
        ),
        migrations.AddField(
            model_name='profil',
            name='adherent_rtg',
            field=models.BooleanField(default=False, verbose_name='Je suis adhérent de Ramene Ta Graine'),
        ),
        migrations.AddField(
            model_name='produit',
            name='asso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bourseLibre.Asso'),
        ),
        migrations.RunPython(combine_names, ),
    ]
