# Generated by Django 2.2.13 on 2020-09-17 18:21

from django.db import migrations, models
import django.db.models.deletion


def refaireSalons(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    msgs_pc = apps.get_model('bourseLibre', 'MessageGeneralPermacat')
    msgs = apps.get_model('bourseLibre', 'MessageGeneral')
    assos = apps.get_model('bourseLibre', 'Asso')
    asso_public, created = assos.objects.get_or_create(nom='Public')
    asso_permacat, created = assos.objects.get_or_create(nom='Permacat')
    for msg in msgs.objects.all():
        msg.asso = asso_public
        msg.save()
    for msg in msgs_pc.objects.all():
        msg.asso = asso_permacat
        msg.save()

class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0033_auto_20200825_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagegeneralrtg',
            name='auteur',
        ),
        migrations.AddField(
            model_name='messagegeneral',
            name='asso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bourseLibre.Asso'),
        ),

        migrations.RunPython(refaireSalons, ),
        migrations.DeleteModel(
            name='MessageGeneralPermacat',
        ),
        migrations.DeleteModel(
            name='MessageGeneralRTG',
        ),
    ]
