# Generated by Django 2.2.13 on 2020-09-17 20:42

from django.db import migrations, models


def refaireSalons(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.

    profils =  apps.get_model('bourseLibre', 'Profil')

    for prof in profils.objects.all():
        if prof.statut_adhesion == 2:
            prof.adherent_permacat = True
            prof.save()
        if prof.statut_adhesion_rtg == 2:
            prof.adherent_rtg = True
            prof.save()

class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0034_auto_20200917_2021'),
    ]

    operations = [
        migrations.RunPython(refaireSalons, ),
    ]
