# Generated by Django 2.2.13 on 2020-10-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0035_profil_statut_adhesio2n'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='adherent_ame',
        ),
        migrations.AddField(
            model_name='profil',
            name='adherent_ga',
            field=models.BooleanField(default=False, verbose_name='Je suis adhérent de Animaux Mieux Etre'),
        ),
        migrations.AddField(
            model_name='profil',
            name='statut_adhesion_ga',
            field=models.IntegerField(choices=[('', '-----------'), (0, "Je souhaite devenir membre de l'association 'GaïArmonie'"), (1, "Je souhaite utiliser le site, mais ne pas devenir membre de l'association GaïArmonie"), (2, "Je suis déjà membre de l'association GaïArmonie")], default='0'),
        ),
    ]
