# Generated by Django 2.2.13 on 2020-10-30 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0036_auto_20201030_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='adherent_rtg',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='statut_adhesion_rtg',
        ),
        migrations.AlterField(
            model_name='profil',
            name='adherent_ga',
            field=models.BooleanField(default=False, verbose_name='Je suis adhérent de Gaïarmonie'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='statut_adhesion_ga',
            field=models.IntegerField(choices=[('', '-----------'), (0, "Je souhaite devenir membre de l'association 'Gaïarmonie'"), (1, "Je souhaite utiliser le site, mais ne pas devenir membre de l'association Gaïarmonie"), (2, "Je suis déjà membre de l'association Gaïarmonie")], default='0'),
        ),
    ]
