# Generated by Django 2.2.13 on 2020-12-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0038_auto_20201030_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='adherent_ga',
        ),
        migrations.AddField(
            model_name='profil',
            name='adherent_rtg',
            field=models.BooleanField(default=False, verbose_name='Je suis adhérent de Ramene Ta Graine'),
        ),
    ]
