# Generated by Django 2.2.13 on 2020-12-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0039_auto_20201219_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='adherent_ga',
            field=models.BooleanField(default=False, verbose_name='Je suis adhérent de Gaïarmonie'),
        ),
    ]
