# Generated by Django 2.2.13 on 2020-12-19 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0040_profil_adherent_ga'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='statut_adhesion_ga',
        ),
    ]
