# Generated by Django 2.2.13 on 2021-01-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0041_remove_profil_statut_adhesion_ga'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='adherent_ga',
        ),
        migrations.AddField(
            model_name='profil',
            name='adherent_fer',
            field=models.BooleanField(default=False, verbose_name='Je suis adhérent de Fermille'),
        ),
    ]
