# Generated by Django 2.2.13 on 2021-02-13 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0042_auto_20210127_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='inscrit_newsletter',
            field=models.BooleanField(default=False, verbose_name="J'accepte de recevoir des emails de Perma.cat"),
        ),
    ]
