# Generated by Django 2.2.13 on 2021-03-12 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0043_auto_20210213_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='cotisation_a_jour',
        ),
    ]
