# Generated by Django 2.2.20 on 2021-05-25 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0046_auto_20210406_2056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profil',
            old_name='adherent_permacat',
            new_name='adherent_pc',
        ),
    ]
