# Generated by Django 2.2.20 on 2021-05-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0047_auto_20210525_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='adherent_gt',
            field=models.BooleanField(default=False, verbose_name='Je suis adhérent de Gardiens de la Terre'),
        ),
    ]
