# Generated by Django 2.2.24 on 2021-07-29 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0048_profil_adherent_gt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profil',
            old_name='is_jardinpartage',
            new_name='adherent_jp',
        ),
    ]
