# Generated by Django 2.2.24 on 2021-08-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0049_auto_20210729_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adresse',
            name='commune',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
