# Generated by Django 2.2.24 on 2021-08-15 08:49

from django.db import migrations, models


def ajouterAsso(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    assos = apps.get_model('bourseLibre', 'Asso')
    asso_scic, created = assos.objects.get_or_create(nom='PermAgora', abreviation="scic", email="permacat66@gmail.com")

class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0050_auto_20210813_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='adherent_scic',
            field=models.BooleanField(default=False, verbose_name="Je suis intéressé par l'asso PermAgora"),
        ),
        migrations.RunPython(ajouterAsso, ),
    ]
