# Generated by Django 2.2.24 on 2021-08-16 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0051_profil_adherent_scic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='adherent_gt',
        ),
    ]
