# Generated by Django 2.2.24 on 2021-08-29 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0053_profil_adherent_ca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='adherent_ca',
            field=models.BooleanField(default=False, verbose_name='Je fais partie de la cité altruiste'),
        ),
    ]
