# Generated by Django 2.2.24 on 2021-08-29 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0054_auto_20210829_2116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profil',
            old_name='adherent_ca',
            new_name='adherent_citealt',
        ),
    ]
