# Generated by Django 2.2.24 on 2021-08-30 19:55

from django.db import migrations

from bourseLibre.models import Suivis, Profil
from bourseLibre.views_admin import send_mass_html_mail
from bourseLibre.constantes import Choix as Choix_global
from actstream import actions
from bourseLibre.settings.production import SERVER_EMAIL

def create_types(apps, schema_editor):
    suivi, created = Suivis.objects.get_or_create(nom_suivi='articles')
    suivi.delete()

    profils = Profil.objects.all()
    listeMails = []
    titre = "MAJ Abonnements mails sur Perma.Cat..."
    for prof in profils:
        suivi, created = Suivis.objects.get_or_create(nom_suivi="articles_public")
        actions.follow(prof, suivi, actor_only=True, send_action=False)

        for nom_suivi in ["articles_" + abreviation for abreviation, nom in Choix_global.abreviationsNomsAsso if getattr(prof, "adherent_" + abreviation) == True] :
            suivi, created = Suivis.objects.get_or_create(nom_suivi=nom_suivi)
            actions.follow(prof, suivi, actor_only=True, send_action=False)

        for nom_suivi in ["agora_" + abreviation for abreviation, nom in Choix_global.abreviationsNomsAsso if getattr(prof, "adherent_" + abreviation) == True] :
            suivi, created = Suivis.objects.get_or_create(nom_suivi=nom_suivi)
            actions.follow(prof, suivi, actor_only=True, send_action=False)

        for nom_suivi in ['projets', 'produits', 'conversations', 'documents', 'albums', 'ateliers', 'suffrages',] :
            suivi, created = Suivis.objects.get_or_create(nom_suivi=nom_suivi)
            actions.follow(prof, suivi, actor_only=True, send_action=False)

        messagetxt = "Bonjour, Vous venez peut etre d'arriver sur le site, ou bien vous êtes inscrit de longue date, alors permettez nous de vous donner quelques nouvelles du site www.Perma.Cat Après les asso Permacat, Ramène Ta Graine et Fermille nous sommes heureux d'accueillir un nouveau collectif : la Cité Altruiste. Bienvenue à eux ! (le groupe est ouvert si vous voulez nous rejoindre...)Nous avons fait de nombreux changements sur le site ces derniers temps, afin de le rendre plus pratique et complet. Par exemple nous pouvons désormais organiser des votes (au jugement majoritaire) directement sur le site, ou bien proposer des ateliers...Afin de laisser plus de choix aux mails que vous voulez recevoir, le système d'abonnement du forum a été revu, et vous pouvez maintenant mieux cibler les infos qui vous arrivent par mail. Par exemple, vous pouvez vous abonner uniquement aux mails du groupe 'Ramène Ta Graine' et/ou 'PermaCat' si vous ne souhaitez pas recevoir les infos des autres groupes par mail, (mais rassurez-vous vous y aurez toujours accès, si vous faite partie du collectif, dans les notifications du site).La mauvaise nouvelle c'est que pour cela nous avons du réinitialiser les abonnements mails de base (forum, altermarché, etc.) de tous les utilisateurs... Donc si vous ne souhaitez pas recevoir de mails, vous pouvez configurer vos abonnements sur votre page de profil -> abonnements Si vous ne souhaitez plus entendre parler de nous, vous pouvez supprimer votre compte en allant sur votre profil à tout moment... (ou en faisant la demande par mail)Sinon, n'hésitez pas à donner de vos nouvelles... et à participer ! Désolé du dérangement, fins aviat !"
        message = "<h2 style='color: #2e6c80;'>Bonjour,</h2> \
<p>Vous venez peut-&ecirc;tre d'arriver sur le site, ou bien vous &ecirc;tes inscrit de longue date, alors permettez nous de vous donner quelques nouvelles du site <a href='https://www.Perma.Cat'>www.Perma.Cat</a></p>\
<p>Apr&egrave;s les asso Permacat, Ram&egrave;ne Ta Graine et Fermille nous sommes heureux d'accueillir un nouveau collectif : la Cit&eacute; Altruiste. Bienvenue &agrave; eux ! (le groupe est ouvert si vous voulez nous rejoindre, ça peut se faire directement sur le site...)</p>\
<p>Nous avons fait de nombreux changements sur le site ces derniers temps, afin de le rendre plus pratique et complet. Par exemple nous pouvons d&eacute;sormais organiser des votes (au jugement majoritaire) directement sur le site, ou bien proposer des ateliers...</p>\
<p>Vous pouvez aussi, si ce n'est d&eacute;j&agrave; fait cette ann&eacute;e, adh&eacute;rer &agrave; PermaCat et/ou Ram&egrave;ne Ta Graine directement en ligne.</p>\
<p>Afin de laisser plus de choix aux mails que vous voulez recevoir, le syst&egrave;me d'abonnement du forum a &eacute;t&eacute; revu, et vous pouvez maintenant mieux cibler les infos qui vous arrivent par mail. Par exemple, vous pouvez vous abonner uniquement aux mails du groupe 'Ram&egrave;ne Ta Graine' et/ou 'PermaCat' si vous ne souhaitez pas recevoir les infos des autres groupes par mail, (mais rassurez-vous vous y aurez toujours acc&egrave;s, si vous faite partie du collectif, dans les notifications du site).</p>\
<p>La mauvaise nouvelle c'est que pour cela nous avons du r&eacute;initialiser les abonnements mails de base (forum, altermarch&eacute;, etc.) de tous les utilisateurs... Donc si vous ne souhaitez pas recevoir de mails, vous pouvez configurer vos abonnements sur <a href='https://www.perma.cat/accounts/profile/'>votre page de profil -&gt; abonnements</a></p>\
<p>Si vous ne souhaitez plus entendre parler de nous, vous pouvez supprimer votre compte en allant sur votre profil &agrave; tout moment... (ou en faisant la demande par mail)</p>\
<p>Sinon, n'h&eacute;sitez pas &agrave; donner de vos nouvelles... et &agrave; participer !</p>\
<p>&nbsp;</p>\
<p>D&eacute;sol&eacute; du d&eacute;rangement,</p>\
<p>fins aviat !</p>"

        listeMails.append((titre, messagetxt, message, SERVER_EMAIL, [prof.email,]))

    send_mass_html_mail(listeMails, fail_silently=False)

class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0055_auto_20210829_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='statut_adhesion',
        ),
      # migrations.RunPython(create_types),
    ]
