# Generated by Django 2.2.24 on 2021-10-10 18:49

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0056_remove_profil_statut_adhesion'),
    ]

    operations = [
        UnaccentExtension()
    ]

    operations = [
    ]
