# Generated by Django 2.2.24 on 2021-11-03 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0057_auto_20211010_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='avatar',
        ),
    ]
