# Generated by Django 2.2.24 on 2021-12-01 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0058_remove_profil_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='adherent_viure',
            field=models.BooleanField(default=False, verbose_name='Je fais partie du collectif Viure !'),
        ),
    ]
