# Generated by Django 2.2.24 on 2021-12-03 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0059_profil_adherent_viure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='adherent_citealt',
            field=models.BooleanField(default=False, verbose_name="Je fais partie de 'la Cité Altruiste"),
        ),
        migrations.AlterField(
            model_name='profil',
            name='adherent_scic',
            field=models.BooleanField(default=False, verbose_name="Je suis intéressé par le collectif 'PermAgora'"),
        ),
        migrations.AlterField(
            model_name='profil',
            name='adherent_viure',
            field=models.BooleanField(default=False, verbose_name="Je fais partie du collectif 'Viure'"),
        ),
    ]
