# Generated by Django 2.2.24 on 2021-12-03 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0060_auto_20211203_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagegeneral',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
