# Generated by Django 2.2.24 on 2021-12-17 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0061_auto_20211203_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagegeneral',
            name='message',
            field=models.TextField(),
        ),
    ]
