# Generated by Django 2.2.24 on 2021-12-17 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0062_auto_20211217_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='adherent_citealt',
            field=models.BooleanField(default=False, verbose_name="Je fais partie de 'la Cité Altruiste'"),
        ),
    ]
