# Generated by Django 2.2.24 on 2022-02-04 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0063_auto_20211217_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='unite_prix',
            field=models.CharField(choices=[('don', 'don'), ('troc', 'troc'), ('pret', 'prêt'), ('G1', 'G1'), ('Soudaqui', 'Soudaqui'), ('SEL', 'SEL'), ('JEU', 'JEU'), ('HE', 'heureEntraide'), ('Autre', 'Négociable')], default='lliure', max_length=8, verbose_name='monnaie'),
        ),
    ]
