# Generated by Django 2.2.27 on 2022-02-14 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0064_auto_20220205_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='adhesion_permacat',
            name='moyen',
            field=models.CharField(choices=[('0', 'Espèce'), ('1', 'HelloAsso'), ('2', 'Cheque')], default='0', max_length=3, verbose_name='Moyen de maiement'),
        ),
    ]
