# Generated by Django 2.2.27 on 2022-02-24 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0067_auto_20220224_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit_listeoffresetdemandes',
            name='souscategorie',
            field=models.CharField(choices=[('Liste', 'Liste')], default='L', max_length=20),
        ),
    ]
