# Generated by Django 2.2.27 on 2022-04-07 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0071_auto_20220407_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adresse',
            name='telephone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
