# Generated by Django 2.2.27 on 2022-04-27 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0072_auto_20220407_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='adherent_bzz2022',
            field=models.BooleanField(default=False, verbose_name="Je fais partie du collectif 'Bzzz'"),
        ),
    ]
