# Generated by Django 2.2.28 on 2022-08-10 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0073_profil_adherent_bzz2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='afficherNbNotifications',
            field=models.BooleanField(default=False, verbose_name='Affichage du nombre de notifications dans le menu'),
        ),
    ]
