# Generated by Django 2.2.28 on 2022-08-16 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0074_profil_affichernbnotifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='InscritSalon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=250)),
                ('auteur', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100)),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de parution')),
                ('date_dernierMessage', models.DateTimeField(blank=True, null=True, verbose_name='Date de Modification')),
                ('dernierMessage', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('public', models.BooleanField(default=False, verbose_name='Salon public ou privé (public si coché)')),
                ('membres', models.ManyToManyField(through='bourseLibre.InscritSalon', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date_dernierMessage',),
            },
        ),
        migrations.CreateModel(
            name='Message_salon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bourseLibre.Salon')),
            ],
        ),
        migrations.AddField(
            model_name='inscritsalon',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bourseLibre.Salon'),
        ),
    ]
