# Generated by Django 2.2.28 on 2022-08-17 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0075_auto_20220816_2305'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationDansSalon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profil_invitant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitant', to=settings.AUTH_USER_MODEL)),
                ('profil_invite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite', to=settings.AUTH_USER_MODEL)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bourseLibre.Salon')),
            ],
        ),
    ]
