# Generated by Django 2.2.28 on 2022-08-17 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0076_invitationdanssalon'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invitationdanssalon',
            unique_together={('profil_invitant', 'profil_invite', 'salon')},
        ),
    ]
