# Generated by Django 2.2.28 on 2022-08-20 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0077_auto_20220817_2251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salon',
            old_name='public',
            new_name='estPublic',
        ),
    ]
