# Generated by Django 2.2.28 on 2022-08-20 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0093_auto_20220820_1018'),
        ('bourseLibre', '0078_auto_20220820_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='article',
            field=models.ForeignKey(blank=True, help_text="L'evenement doit etre associé à un article existant (sinon créez un article avec une date)", null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Article'),
        ),
    ]
