# Generated by Django 2.2.28 on 2022-10-30 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0082_inscritsalon_date_creation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adhesion_asso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_cotisation', models.DateField(verbose_name='Date de la cotisation')),
                ('montant', models.CharField(max_length=50, verbose_name="Montant de l'adhesion")),
                ('moyen', models.CharField(choices=[('0', 'Espèce'), ('1', 'HelloAsso'), ('2', 'Cheque')], default='0', max_length=3, verbose_name='Moyen de maiement')),
                ('asso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bourseLibre.Asso')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur Permacat')),
            ],
        ),
    ]
