# Generated by Django 2.2.28 on 2022-10-30 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0083_adhesion_asso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adhesion_asso',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur '),
        ),
    ]
