# Generated by Django 2.2.28 on 2023-01-02 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bourseLibre', '0085_auto_20221124_2007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salon',
            options={'ordering': ('titre',)},
        ),
        migrations.AlterField(
            model_name='salon',
            name='article',
            field=models.ForeignKey(blank=True, help_text='Le salon doit être associé à un article existant (sinon créez un article avec une date)', null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Article'),
        ),
    ]
