# Generated by Django 2.2.8 on 2020-06-08 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardinpartage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='categorie',
            field=models.CharField(choices=[('Discu', 'Discussion générale'), ('Organisation', 'Organisation'), ('Potager', 'Au potager'), ('PPAM', 'PPAM'), ('Arbres', 'Les arbres au jardin'), ('Agenda', 'Agenda'), ('Documentation', 'Documentation'), ('Autre', 'Autre')], default='Annonce', max_length=30, verbose_name='categorie'),
        ),
    ]
