# Generated by Django 2.2.8 on 2020-06-08 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardinpartage', '0002_auto_20200608_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='categorie',
            field=models.CharField(choices=[('Discu', 'Information'), ('Organisation', 'Organisation'), ('Potager', 'Au potager'), ('PPAM', 'PPAM'), ('Arbres', 'Les arbres au jardin'), ('Agenda', 'Agenda'), ('todo', 'A faire'), ('Documentation', 'Documentation'), ('Autre', 'Autre')], default='Discu', max_length=30, verbose_name='categorie'),
        ),
    ]
