# Generated by Django 2.2.8 on 2020-06-14 23:25

from django.db import migrations, models

#def combine_names(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    # article = apps.get_model('jardinpartage', 'Article')
    # assos = apps.get_model('bourseLibre', 'Asso')
    # asso_public, created = assos.objects.get_or_create(nom='Public')
    # asso_permacat, created = assos.objects.get_or_create(nom='Permacat')
    # for prod in article.objects.all():
    #     if prod.estPublic:
     #        prod.asso = asso_public
     #    else:
     #        prod.asso = asso_permacat
      #   prod.save()


class Migration(migrations.Migration):

    dependencies = [
        ('jardinpartage', '0003_auto_20200609_0106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participe', models.BooleanField(default=False, verbose_name='Je suis intéressé.e par les jardins partagés')),
            ],
        ),
    #migrations.RunPython(combine_names, ),


    ]
