# Generated by Django 2.2.13 on 2020-09-17 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardinpartage', '0005_article_asso'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='jardin',
            field=models.CharField(choices=[('0', 'Jardi Per Tots'), ('1', 'JardiPal')], default='0', max_length=30, verbose_name='Jardin'),
        ),
    ]
