# Generated by Django 2.2.13 on 2020-09-17 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardinpartage', '0009_auto_20200917_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='jardin',
            field=models.CharField(choices=[('0', 'Tous les jardins'), ('1', 'Jardi Per Tots'), ('2', 'JardiPal')], default='0', max_length=30, verbose_name='Jardin'),
        ),
    ]
