# Generated by Django 2.2.13 on 2020-12-18 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardinpartage', '0012_auto_20201216_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='jardin',
            field=models.CharField(choices=[('0', 'Tous les jardins'), ('1', 'Jardi Per Tots'), ('2', 'JardiPal'), ('3', 'Jardins de Lurçat')], default='0', max_length=30, verbose_name='Jardin'),
        ),
    ]
