# Generated by Django 2.2.13 on 2021-03-15 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jardinpartage', '0014_auto_20210222_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evenement',
            old_name='titre',
            new_name='titre_even',
        ),
    ]
