# Generated by Django 2.2.24 on 2021-08-30 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardinpartage', '0015_auto_20210528_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='start_time',
            field=models.DateTimeField(blank=True, help_text='jj/mm/année', null=True, verbose_name="Date de l'évenement (pour affichage dans l'agenda) - date de début si l'événement a lieu sur plusieurs jours "),
        ),
    ]
