# Generated by Django 2.2.20 on 2021-05-26 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jardinpartage', '0015_auto_20210315_1221'),
        ('jardinpartage', '0015_auto_20210526_2243'),
    ]

    operations = [
    ]
