# Generated by Django 2.2.24 on 2021-09-07 21:25

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('jardinpartage', '0017_auto_20210907_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='end_time',
            field=models.DateField(blank=True, help_text='jj/mm/année', null=True, verbose_name='Date de fin (optionnel pour un evenement sur plusieurs jours)'),
        ),
    ]
