# Generated by Django 2.2.28 on 2022-11-13 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardinpartage', '0020_auto_20211125_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='jardin',
            field=models.CharField(choices=[('0', 'Tous les jardins'), ('1', 'Jardi Per Tots'), ('2', 'Jardin de Palau'), ('3', 'Jardins de Lurçat'), ('4', 'Gardiens de la Terre'), ('5', 'Fermille'), ('6', 'Chez Claire')], default='0', max_length=30, verbose_name='Jardin'),
        ),
    ]
