# Generated by Django 2.2.28 on 2022-11-27 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jardinpartage', '0021_auto_20221113_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='article',
            field=models.ForeignKey(help_text="L'evenement doit etre associé à un article", on_delete=django.db.models.deletion.CASCADE, to='jardinpartage.Article'),
        ),
    ]
