# Generated by Django 2.2.27 on 2022-03-24 22:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agoratransition', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message_agora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('nom', models.CharField(max_length=250, verbose_name='Nom prénom / Raison sociale')),
                ('msg', models.TextField(verbose_name='Message')),
            ],
        ),
        migrations.CreateModel(
            name='Proposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250, verbose_name='Nom de la structure*')),
                ('email', models.EmailField(default='test@perma.cat', max_length=254, verbose_name='Email*')),
                ('telephone', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Le numéro de téléphone doit contenir 10 chiffres', regex='^\\d{9,10}$')], verbose_name='Numéro de téléphone')),
                ('proposition', models.TextField(verbose_name='Proposition de question / table ronde*')),
                ('animeParProposant', models.BooleanField(default=False, verbose_name='Je suis pret.e à animer une table ronde à ce sujet')),
                ('date_inscription', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscrition")),
            ],
        ),
        migrations.RemoveField(
            model_name='inscriptionexposant',
            name='nom_structure',
        ),
        migrations.RemoveField(
            model_name='inscriptionexposant',
            name='user',
        ),
        migrations.AddField(
            model_name='inscriptionexposant',
            name='commentaire',
            field=models.TextField(blank=True, verbose_name='Commentaire / message à passer'),
        ),
        migrations.AddField(
            model_name='inscriptionexposant',
            name='email',
            field=models.EmailField(default='test@perma.cat', max_length=254, verbose_name='Email*'),
        ),
        migrations.AddField(
            model_name='inscriptionexposant',
            name='nom',
            field=models.CharField(blank=True, max_length=250, verbose_name='Nom Prénom / Raison sociale*'),
        ),
        migrations.AlterField(
            model_name='inscriptionexposant',
            name='telephone',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Le numéro de téléphone doit contenir 10 chiffres', regex='^\\d{9,10}$')], verbose_name='Numéro de téléphone'),
        ),
        migrations.AlterField(
            model_name='inscriptionexposant',
            name='type_inscription',
            field=models.CharField(choices=[('0', 'Particulier'), ('1', 'Association'), ('2', 'Institution'), ('3', 'Entreprise'), ('4', 'autre')], default='0', max_length=10, verbose_name='Type de structure'),
        ),
    ]
