# Generated by Django 2.2.27 on 2022-03-24 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agoratransition', '0002_auto_20220324_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscriptionexposant',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email*'),
        ),
        migrations.AlterField(
            model_name='proposition',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email*'),
        ),
    ]
