# Generated by Django 2.2.27 on 2022-03-24 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agoratransition', '0004_auto_20220324_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscriptionexposant',
            name='telephone',
            field=models.CharField(blank=True, max_length=10, verbose_name='Numéro de téléphone'),
        ),
        migrations.AlterField(
            model_name='proposition',
            name='nom',
            field=models.CharField(max_length=250, verbose_name='Nom Prénom / Raison sociale*'),
        ),
        migrations.AlterField(
            model_name='proposition',
            name='telephone',
            field=models.CharField(blank=True, max_length=10, verbose_name='Numéro de téléphone'),
        ),
    ]
