# Generated by Django 2.2.27 on 2022-03-26 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agoratransition', '0005_auto_20220324_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposition',
            name='animeParProposant',
            field=models.BooleanField(default=False, null=True, verbose_name='Je suis pret.e à animer une table ronde à ce sujet'),
        ),
    ]
