# Generated by Django 2.2.20 on 2021-05-26 14:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bourseLibre', '0048_profil_adherent_gt'),
        ('sites', '0002_alter_domain_unique'),
        ('photologue', '0014_gallery_auteur'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gallery',
            new_name='Album',
        ),
    ]
