# Generated by Django 2.2.20 on 2021-05-26 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0015_auto_20210526_1623'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'get_latest_by': 'date_added', 'ordering': ['-date_added'], 'verbose_name': 'album', 'verbose_name_plural': 'galleries'},
        ),
    ]
