# Generated by Django 2.2.20 on 2021-05-26 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0020_auto_20210526_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='asso',
        ),
    ]
