# Generated by Django 2.2.20 on 2021-05-26 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0021_remove_photo_asso'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='estModifiable',
            field=models.BooleanField(default=False, verbose_name='Modifiable par les autres'),
        ),
    ]
