# Generated by Django 2.2.24 on 2021-06-15 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('bourseLibre', '0048_profil_adherent_gt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photologue', '0023_auto_20210527_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(help_text='max. 5 Mo', upload_to='photologue', verbose_name='image'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.FileField(upload_to='documents/%Y/%m/%d', verbose_name='Document')),
                ('titre', models.CharField(max_length=250, unique=True, verbose_name='titre')),
                ('slug', models.SlugField(help_text='A "slug" is a unique URL-friendly title for an object.', max_length=250, unique=True, verbose_name='slug')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name="date d'ajout")),
                ('asso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bourseLibre.Asso')),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='Liste de mots-clés séparés par une virgule', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Mots clés')),
            ],
        ),
    ]
