# Generated by Django 2.2.24 on 2021-06-15 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0024_auto_20210615_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name="date d'ajout"),
        ),
    ]
