# Generated by Django 2.2.24 on 2021-10-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0026_auto_20210704_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(help_text='max. 20 Mo', upload_to='photologue', verbose_name='image'),
        ),
    ]
