# Generated by Django 2.2.27 on 2022-02-17 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0080_auto_20211203_1927'),
        ('photologue', '0027_auto_20211010_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Article'),
        ),
    ]
