# Generated by Django 2.2.27 on 2022-07-25 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('permagora', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentaire_charte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('type_message', models.CharField(choices=[('0', 'Commentaire'), ('1', 'Coquille'), ('2', 'Réflexion')], default='0', max_length=10, verbose_name='type de commentaire')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Domaine_charte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.TextField()),
                ('slug', models.SlugField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Message_permagora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('type_message', models.CharField(choices=[('0', 'Commentaire'), ('1', 'Coquille'), ('2', 'Réflexion')], default='0', max_length=10, verbose_name='type de commentaire')),
                ('type_article', models.CharField(choices=[('0', 'intro'), ('1', 'constat'), ('2', 'preconisations'), ('3', 'charte'), ('4', 'liens'), ('5', 'accueil')], default='0', max_length=10, verbose_name='reaction à')),
                ('valide', models.BooleanField(default=False, verbose_name='validé')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Proposition_charte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.TextField()),
                ('explication', models.TextField(blank=True)),
                ('compteur_plus', models.IntegerField(default=0)),
                ('compteur_moins', models.IntegerField(default=0)),
                ('slug', models.SlugField(max_length=100)),
                ('domaine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permagora.Domaine_charte')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_vote', models.CharField(choices=[(0, 'neutre'), (1, 'plus'), (2, 'moins')], default='0', max_length=10, verbose_name='type de commentaire')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('proposition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permagora.Proposition_charte')),
            ],
        ),
        migrations.RemoveField(
            model_name='message',
            name='auteur',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Adresse',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Profil',
        ),
        migrations.AddField(
            model_name='commentaire_charte',
            name='proposition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permagora.Proposition_charte'),
        ),
    ]
