# Generated by Django 2.2.27 on 2022-07-25 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permagora', '0002_auto_20220725_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposition_charte',
            name='explication',
        ),
        migrations.AddField(
            model_name='proposition_charte',
            name='actions',
            field=models.TextField(blank=True, null=True, verbose_name='Actions effectuées ou envisagées'),
        ),
        migrations.AddField(
            model_name='proposition_charte',
            name='besoins',
            field=models.TextField(blank=True, null=True, verbose_name='Besoins pour mettre en place les solutions'),
        ),
        migrations.AddField(
            model_name='proposition_charte',
            name='contexte',
            field=models.TextField(blank=True, null=True, verbose_name='Matériel/outils nécessaires'),
        ),
        migrations.AddField(
            model_name='proposition_charte',
            name='existant',
            field=models.TextField(blank=True, null=True, verbose_name='Existant déjà sur le territoire (association, projet, ...)'),
        ),
        migrations.AddField(
            model_name='proposition_charte',
            name='ideal',
            field=models.TextField(blank=True, null=True, verbose_name="Ce qu'il faudrait faire idéalement"),
        ),
        migrations.AddField(
            model_name='proposition_charte',
            name='ressources',
            field=models.TextField(blank=True, null=True, verbose_name='Ressources associées (articles, vidéos, ...)'),
        ),
    ]
