# Generated by Django 2.2.27 on 2022-07-25 20:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('permagora', '0003_auto_20220725_1120'),
    ]

    operations = [

        migrations.CreateModel(
            name='PropositionCharte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation',
                 models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de parution')),
                ('titre', models.CharField(max_length=300, verbose_name='Question')),
                ('ressources',
                 models.TextField(blank=True, null=True, verbose_name='Ressources associées (articles, vidéos, ...)')),
                ('contexte', models.TextField(blank=True, null=True, verbose_name='Matériel/outils nécessaires')),
                ('besoins',
                 models.TextField(blank=True, null=True, verbose_name='Besoins pour mettre en place les solutions')),
                ('ideal', models.TextField(blank=True, null=True, verbose_name="Ce qu'il faudrait faire idéalement")),
                ('existant', models.TextField(blank=True, null=True,
                                              verbose_name='Existant déjà sur le territoire (association, projet, ...)')),
                ('actions', models.TextField(blank=True, null=True, verbose_name='Actions effectuées ou envisagées')),
                ('compteur_plus', models.IntegerField(default=0)),
                ('compteur_moins', models.IntegerField(default=0)),
                ('slug', models.SlugField(max_length=100)),
                ('pole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permagora.Domaine_charte')),
            ],
        ),
        migrations.RemoveField(
            model_name='proposition_charte',
            name='actions',
        ),
        migrations.RemoveField(
            model_name='proposition_charte',
            name='besoins',
        ),
        migrations.RemoveField(
            model_name='proposition_charte',
            name='compteur_moins',
        ),
        migrations.RemoveField(
            model_name='proposition_charte',
            name='compteur_plus',
        ),
        migrations.RemoveField(
            model_name='proposition_charte',
            name='contexte',
        ),
        migrations.RemoveField(
            model_name='proposition_charte',
            name='domaine',
        ),
        migrations.RemoveField(
            model_name='proposition_charte',
            name='existant',
        ),
        migrations.RemoveField(
            model_name='proposition_charte',
            name='ideal',
        ),
        migrations.RemoveField(
            model_name='proposition_charte',
            name='ressources',
        ),
        migrations.RemoveField(
            model_name='proposition_charte',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='proposition_charte',
            name='titre',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='proposition',
        ),
        migrations.AddField(
            model_name='proposition_charte',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de parution'),
        ),
        migrations.AlterField(
            model_name='commentaire_charte',
            name='proposition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permagora.PropositionCharte'),
        ),
    ]
