# Generated by Django 2.2.27 on 2022-07-25 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permagora', '0004_auto_20220725_2253'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Proposition_charte',
        ),
    ]
