# Generated by Django 2.2.27 on 2022-07-25 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permagora', '0006_delete_proposition_charte'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Domaine_charte',
            new_name='Pole_charte',
        ),
    ]
