# Generated by Django 2.2.27 on 2022-07-25 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permagora', '0007_auto_20220725_2312'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pole_charte',
            new_name='PoleCharte',
        ),
    ]
