# Generated by Django 2.2.27 on 2022-07-31 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('permagora', '0008_auto_20220725_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='propositioncharte',
            name='auteur',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
