# Generated by Django 2.2.27 on 2022-07-31 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permagora', '0009_propositioncharte_auteur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propositioncharte',
            name='actions',
            field=models.TextField(blank=True, null=True, verbose_name='Actions effectuées ou envisagées à court terme'),
        ),
        migrations.AlterField(
            model_name='propositioncharte',
            name='besoins',
            field=models.TextField(blank=True, null=True, verbose_name='Besoins et limites pour la mise en place des solutions'),
        ),
        migrations.AlterField(
            model_name='propositioncharte',
            name='contexte',
            field=models.TextField(blank=True, null=True, verbose_name='Contexte de la problématique (enjeux locaux)'),
        ),
        migrations.AlterField(
            model_name='propositioncharte',
            name='existant',
            field=models.TextField(blank=True, null=True, verbose_name="Existant (ce qu'il se fait déjà sur le territoir : association, projet, ...)"),
        ),
        migrations.AlterField(
            model_name='propositioncharte',
            name='titre',
            field=models.CharField(max_length=300, verbose_name='Question / problématique'),
        ),
    ]
