# Generated by Django 2.2.27 on 2022-07-31 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permagora', '0010_auto_20220731_2255'),
    ]

    operations = [
    ]
