# Generated by Django 2.2.27 on 2022-07-31 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permagora', '0011_vote_proposition'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
