# Generated by Django 2.2.27 on 2022-08-01 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permagora', '0014_signataire'),
    ]

    operations = [
        migrations.AddField(
            model_name='signataire',
            name='apparait_visible',
            field=models.BooleanField(default=False, verbose_name="J'accepte d'apparaitre sur la liste des soutiens"),
        ),
        migrations.AlterField(
            model_name='message_permagora',
            name='type_article',
            field=models.CharField(choices=[('0', 'intro'), ('1', 'constat'), ('2', 'preconisations'), ('3', 'charte'), ('4', 'liens'), ('5', 'accueil'), ('6', 'preambule')], default='0', max_length=10, verbose_name='reaction à'),
        ),
    ]
