# Generated by Django 2.2.28 on 2022-08-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permagora', '0016_polecharte_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message_permagora',
            name='type_article',
            field=models.CharField(choices=[('0', 'intro'), ('1', 'constat'), ('2', 'preconisations'), ('3', 'charte'), ('4', 'liens'), ('5', 'accueil'), ('6', 'présentation'), ('7', 'organisation')], default='0', max_length=10, verbose_name='reaction à'),
        ),
    ]
