# Generated by Django 2.2.28 on 2022-08-23 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permagora', '0018_auto_20220815_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_article', models.CharField(choices=[('0', 'intro'), ('1', 'constat'), ('2', 'preconisations'), ('3', 'charte'), ('4', 'liens'), ('5', 'accueil'), ('6', 'présentation'), ('7', 'organisation')], default='0', max_length=10, verbose_name='reaction à')),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
