# Generated by Django 2.2.28 on 2022-08-23 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permagora', '0019_genericmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericmodel',
            name='type_article',
            field=models.CharField(choices=[('0', 'intro'), ('1', 'constat'), ('2', 'preconisations'), ('3', 'propositions'), ('4', 'liens'), ('5', 'accueil'), ('6', 'présentation'), ('7', 'organisation')], default='0', max_length=10, verbose_name='type_article'),
        ),
        migrations.AlterField(
            model_name='message_permagora',
            name='type_article',
            field=models.CharField(choices=[('0', 'intro'), ('1', 'constat'), ('2', 'preconisations'), ('3', 'propositions'), ('4', 'liens'), ('5', 'accueil'), ('6', 'présentation'), ('7', 'organisation')], default='0', max_length=10, verbose_name='reaction à'),
        ),
    ]
